export type EnterpriseAutomationFeatureKey =
  | 'closeChecklistScoring'
  | 'invoiceMatchingAssistant'
  | 'supplierInvoiceOcrTriage'
  | 'paymentRunOptimization'
  | 'promiseReliabilityScore'
  | 'salesTaxAnomalyDetector'
  | 'payrollVarianceExplainability'
  | 'hrDocumentExpiryBoard'
  | 'purchaseRequestPolicy'
  | 'replenishmentAutopilot'
  | 'serializedTraceability'
  | 'recallCommunicationCenter'
  | 'productionFeasibility'
  | 'maintenancePrioritizer'
  | 'fleetRouteCompliance'
  | 'projectMarginWarning'
  | 'serviceContractProfitability'
  | 'customerPortalAdoption'
  | 'supplierPortalAdoption'
  | 'accountantPortalSla'
  | 'dgiReadinessScore'
  | 'cnssReadinessScore'
  | 'amoReconciliationInsight'
  | 'professionalTaxVault'
  | 'legalArchiveCompleteness'
  | 'bankImportDuplicateGuard'
  | 'cashboxRootCause'
  | 'posOfflineRisk'
  | 'branchStockBalancing'
  | 'landedCostAutomation'
  | 'fxRevaluation'
  | 'recurringInvoiceMonitor'
  | 'usageBillingAudit'
  | 'tenantHealthForecast'
  | 'migrationReadiness'
  | 'releaseImpactSimulator'
  | 'accessReviewCampaign'
  | 'apiKeyRotationCampaign'
  | 'webhookContractTesting'
  | 'biExportCatalog';

export type EnterpriseAutomationMetric = { label: string; path: string; format?: 'money' | 'count' | 'boolean' };

export type EnterpriseAutomationFeatureDefinition = {
  key: EnterpriseAutomationFeatureKey;
  title: string;
  domain: string;
  route: string;
  description: string;
  metrics: EnterpriseAutomationMetric[];
  controls: string[];
};

export const enterpriseAutomationFeatureDefinitions: EnterpriseAutomationFeatureDefinition[] = [
  { key: 'closeChecklistScoring', title: 'Scoring checklist clôture', domain: 'Clôture', route: '/enterprise-automation/automated-close-checklist-scoring-page', description: 'Score de clôture avec journaux, rapprochements, TVA, paie, preuves et owner bloqueur.', metrics: [{ label: 'Score', path: 'score' }, { label: 'Journaux', path: 'journals' }, { label: 'Statut', path: 'status' }], controls: ['Journaux', 'Rapprochements', 'TVA', 'Preuves'] },
  { key: 'invoiceMatchingAssistant', title: 'Assistant matching factures', domain: 'Trésorerie', route: '/enterprise-automation/intelligent-invoice-matching-assistant-page', description: 'Rapprochement assisté des factures client avec lignes banque, confiance et exceptions.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Confiance', path: 'rows.0.confidence' }, { label: 'Statut', path: 'status' }], controls: ['Facture', 'Banque', 'Confiance', 'Exception'] },
  { key: 'supplierInvoiceOcrTriage', title: 'Triage OCR factures fournisseurs', domain: 'Achats', route: '/enterprise-automation/supplier-invoice-ocr-triage-page', description: 'Triage OCR fournisseur avec totaux extraits, confiance TVA, doublons et circuit approbation.', metrics: [{ label: 'Documents', path: 'rows', format: 'count' }, { label: 'Confiance TVA', path: 'rows.0.vatConfidence' }, { label: 'Statut', path: 'status' }], controls: ['OCR', 'TVA', 'Doublon', 'Approbation'] },
  { key: 'paymentRunOptimization', title: 'Optimisation run paiement', domain: 'Achats', route: '/enterprise-automation/payment-run-optimization-page', description: 'Optimisation paiements fournisseurs avec limite cash, priorités, remises et report proposé.', metrics: [{ label: 'Cash limite', path: 'cashLimit', format: 'money' }, { label: 'Propositions', path: 'proposals', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Cash', 'Échéance', 'Priorité', 'Remise'] },
  { key: 'promiseReliabilityScore', title: 'Score promesses client', domain: 'Recouvrement', route: '/enterprise-automation/receivable-promise-reliability-score-page', description: 'Reliability score des promesses de paiement avec historique, kept rate et impact crédit.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Kept rate', path: 'rows.0.keptRate' }, { label: 'Statut', path: 'status' }], controls: ['Historique', 'Promesse', 'Relance', 'Crédit'] },
  { key: 'salesTaxAnomalyDetector', title: 'Détecteur anomalies TVA ventes', domain: 'Fiscalité', route: '/enterprise-automation/sales-tax-anomaly-detector-page', description: 'Détection anomalies TVA ventes par ligne facture, exonération, taux attendu et workflow correction.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Taux', path: 'rows.0.vatRate' }, { label: 'Statut', path: 'status' }], controls: ['Facture', 'Taux TVA', 'Exonération', 'Correction'] },
  { key: 'payrollVarianceExplainability', title: 'Explication variance paie', domain: 'Paie', route: '/enterprise-automation/payroll-variance-explainability-page', description: 'Explainability paie avec net précédent, net courant, drivers IR/CNSS/AMO et note approbation.', metrics: [{ label: 'Salariés', path: 'rows', format: 'count' }, { label: 'Net courant', path: 'rows.0.currentNet', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['IR', 'CNSS', 'AMO', 'Validation'] },
  { key: 'hrDocumentExpiryBoard', title: 'Board échéances documents RH', domain: 'RH', route: '/enterprise-automation/hr-compliance-document-expiry-board-page', description: 'Board conformité RH avec documents salariés, expiry, sévérité et preuve restreinte.', metrics: [{ label: 'Documents', path: 'rows', format: 'count' }, { label: 'Sévérité', path: 'rows.0.severity' }, { label: 'Statut', path: 'status' }], controls: ['Document', 'Expiry', 'Sévérité', 'Preuve'] },
  { key: 'purchaseRequestPolicy', title: 'Moteur politique demandes achat', domain: 'Achats', route: '/enterprise-automation/purchase-request-policy-engine-page', description: 'Moteur politique achats avec requester, budget, chemin approbation, blocage et audit.', metrics: [{ label: 'Demandes', path: 'rows', format: 'count' }, { label: 'Budget', path: 'rows.0.budget', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Requester', 'Budget', 'Approbation', 'Audit'] },
  { key: 'replenishmentAutopilot', title: 'Autopilot réapprovisionnement', domain: 'Stock', route: '/enterprise-automation/inventory-replenishment-autopilot-page', description: 'Autopilot stock avec forecast, lead time fournisseur, quantité suggérée et statut approbation.', metrics: [{ label: 'Articles', path: 'rows', format: 'count' }, { label: 'Quantité suggérée', path: 'rows.0.suggestedQuantity' }, { label: 'Statut', path: 'status' }], controls: ['Forecast', 'Lead time', 'Quantité', 'Approbation'] },
  { key: 'serializedTraceability', title: 'Traçabilité actifs sérialisés', domain: 'Stock', route: '/enterprise-automation/serialized-asset-traceability-dashboard-page', description: 'Dashboard traçabilité sérialisée avec site client, garantie, historique service et preuve.', metrics: [{ label: 'Séries', path: 'rows', format: 'count' }, { label: 'Site', path: 'rows.0.customerSite' }, { label: 'Statut', path: 'status' }], controls: ['Série', 'Site', 'Garantie', 'Preuve'] },
  { key: 'recallCommunicationCenter', title: 'Centre communication rappel lot', domain: 'Qualité', route: '/enterprise-automation/batch-recall-communication-center-page', description: 'Centre rappel lot avec clients affectés, message, réponse et archive.', metrics: [{ label: 'Lot', path: 'lot' }, { label: 'Clients', path: 'affectedCustomers', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Lot', 'Clients', 'Message', 'Archive'] },
  { key: 'productionFeasibility', title: 'Checker faisabilité production', domain: 'Production', route: '/enterprise-automation/production-plan-feasibility-checker-page', description: 'Vérification plan production avec BOM, capacité main-d’oeuvre, machines et contrainte matière.', metrics: [{ label: 'BOM', path: 'bomAvailability' }, { label: 'Capacité', path: 'laborCapacity' }, { label: 'Statut', path: 'status' }], controls: ['BOM', 'Main-d’oeuvre', 'Machine', 'Matière'] },
  { key: 'maintenancePrioritizer', title: 'Priorisation ordres maintenance', domain: 'Maintenance', route: '/enterprise-automation/maintenance-work-order-prioritizer-page', description: 'Priorisation maintenance avec criticité actif, downtime, pièces, SLA et technicien.', metrics: [{ label: 'Ordres', path: 'rows', format: 'count' }, { label: 'Risque', path: 'rows.0.downtimeRisk' }, { label: 'Statut', path: 'status' }], controls: ['Criticité', 'Downtime', 'Pièces', 'SLA'] },
  { key: 'fleetRouteCompliance', title: 'Monitor conformité routes flotte', domain: 'Flotte', route: '/enterprise-automation/fleet-route-compliance-monitor-page', description: 'Conformité routes flotte avec chauffeur, preuve GPS, anomalie fuel et sign-off manager.', metrics: [{ label: 'Véhicules', path: 'rows', format: 'count' }, { label: 'Sign-off', path: 'rows.0.managerSignOff' }, { label: 'Statut', path: 'status' }], controls: ['Chauffeur', 'GPS', 'Fuel', 'Manager'] },
  { key: 'projectMarginWarning', title: 'Alerte précoce marge projet', domain: 'Projets', route: '/enterprise-automation/project-margin-early-warning-page', description: 'Early warning projets avec budget, coût engagé, timesheets, facturation et action corrective.', metrics: [{ label: 'Projets', path: 'rows', format: 'count' }, { label: 'Budget', path: 'rows.0.budget', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Budget', 'Coûts', 'Timesheets', 'Facturation'] },
  { key: 'serviceContractProfitability', title: 'Profitabilité contrats service', domain: 'Services', route: '/enterprise-automation/service-contract-profitability-monitor-page', description: 'Profitabilité contrats service avec SLA, heures support, revenu et recommandation renouvellement.', metrics: [{ label: 'Contrats', path: 'rows', format: 'count' }, { label: 'Revenu', path: 'rows.0.revenue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['SLA', 'Support', 'Revenu', 'Renouvellement'] },
  { key: 'customerPortalAdoption', title: 'Adoption portail client', domain: 'Portails', route: '/enterprise-automation/customer-portal-adoption-tracker-page', description: 'Tracker adoption portail client avec invitations, connexions, vues facture, paiements et nudges.', metrics: [{ label: 'Invitations', path: 'invitations' }, { label: 'Connexions', path: 'logins' }, { label: 'Statut', path: 'status' }], controls: ['Invitation', 'Login', 'Factures', 'Paiements'] },
  { key: 'supplierPortalAdoption', title: 'Adoption portail fournisseur', domain: 'Portails', route: '/enterprise-automation/supplier-portal-adoption-tracker-page', description: 'Tracker adoption portail fournisseur avec uploads documents, réponses devis, litiges et owner.', metrics: [{ label: 'Invitations', path: 'invitations' }, { label: 'Uploads', path: 'documentUploads' }, { label: 'Statut', path: 'status' }], controls: ['Invitation', 'Document', 'Devis', 'Litige'] },
  { key: 'accountantPortalSla', title: 'SLA portail comptable', domain: 'Comptables', route: '/enterprise-automation/accountant-portal-sla-board-page', description: 'Board SLA comptable avec documents en attente, âge revue, deadline et escalade.', metrics: [{ label: 'Revues', path: 'rows', format: 'count' }, { label: 'Âge', path: 'rows.0.reviewAge' }, { label: 'Statut', path: 'status' }], controls: ['Documents', 'Âge', 'Deadline', 'Escalade'] },
  { key: 'dgiReadinessScore', title: 'Score readiness déclaration DGI', domain: 'Fiscalité', route: '/enterprise-automation/dgi-declaration-readiness-score-page', description: 'Score DGI avec TVA, mentions facture, preuves, statut adapter et blocker légal.', metrics: [{ label: 'Score', path: 'score' }, { label: 'Preuves', path: 'evidence' }, { label: 'Statut', path: 'status' }], controls: ['TVA', 'Mentions', 'Preuves', 'Adapter'] },
  { key: 'cnssReadinessScore', title: 'Score readiness déclaration CNSS', domain: 'Paie', route: '/enterprise-automation/cnss-declaration-readiness-score-page', description: 'Score CNSS avec run paie, identifiants salariés, contributions, Damancom et blocker.', metrics: [{ label: 'Identifiants', path: 'employeeIdentifiers' }, { label: 'Coût employeur', path: 'contributionTotals', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Run paie', 'CNSS', 'Damancom', 'Blocker'] },
  { key: 'amoReconciliationInsight', title: 'Insight rapprochement AMO paie', domain: 'Paie', route: '/enterprise-automation/amo-payroll-reconciliation-insight-page', description: 'Rapprochement AMO avec brut paie, base AMO, parts salarié/employeur et variance.', metrics: [{ label: 'Brut', path: 'grossPayroll', format: 'money' }, { label: 'Part employeur', path: 'employerShare', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Brut', 'Base AMO', 'Salarié', 'Employeur'] },
  { key: 'professionalTaxVault', title: 'Coffre preuves taxe professionnelle', domain: 'Fiscalité', route: '/enterprise-automation/professional-tax-evidence-vault-page', description: 'Coffre taxe professionnelle avec établissement, commune, valeur locative, archive et rappel.', metrics: [{ label: 'Établissements', path: 'rows', format: 'count' }, { label: 'Valeur', path: 'rows.0.rentalValue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Commune', 'Valeur', 'Archive', 'Rappel'] },
  { key: 'legalArchiveCompleteness', title: 'Complétude archive légale', domain: 'Archive', route: '/enterprise-automation/legal-archive-completeness-dashboard-page', description: 'Complétude archive légale avec types documents, durée conservation, checksum et owner.', metrics: [{ label: 'Documents', path: 'rows', format: 'count' }, { label: 'Manquant', path: 'rows.0.missingEvidence', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Type', 'Conservation', 'Checksum', 'Owner'] },
  { key: 'bankImportDuplicateGuard', title: 'Garde doublons imports bancaires', domain: 'Banque', route: '/enterprise-automation/bank-import-duplicate-guard-page', description: 'Prévention doublons import bancaire avec référence relevé, hash, imports matchés et reviewer.', metrics: [{ label: 'Imports matchés', path: 'matchedImports' }, { label: 'Prévention', path: 'preventionStatus' }, { label: 'Hash', path: 'hash' }], controls: ['Référence', 'Hash', 'Doublon', 'Reviewer'] },
  { key: 'cashboxRootCause', title: 'Assistant cause racine écart caisse', domain: 'POS', route: '/enterprise-automation/cashbox-variance-root-cause-assistant-page', description: 'Assistant écart caisse avec cash attendu, compté, variance, raison probable et action.', metrics: [{ label: 'Écart', path: 'variance', format: 'money' }, { label: 'Raison', path: 'likelyReason' }, { label: 'Statut', path: 'status' }], controls: ['Attendu', 'Compté', 'Variance', 'Action'] },
  { key: 'posOfflineRisk', title: 'Monitor risque POS offline', domain: 'POS', route: '/enterprise-automation/pos-offline-risk-monitor-page', description: 'Monitor risque POS offline avec device, queue pending, âge, conflit et priorité sync.', metrics: [{ label: 'Devices', path: 'rows', format: 'count' }, { label: 'Priorité', path: 'rows.0.syncPriority' }, { label: 'Statut', path: 'status' }], controls: ['Device', 'Queue', 'Âge', 'Sync'] },
  { key: 'branchStockBalancing', title: 'Assistant équilibrage stock agences', domain: 'Stock', route: '/enterprise-automation/multi-branch-stock-balancing-assistant-page', description: 'Assistant équilibrage stock multi-agences avec source, cible, demande, coût transfert et approbation.', metrics: [{ label: 'Articles', path: 'rows', format: 'count' }, { label: 'Coût', path: 'rows.0.transferCost', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Source', 'Cible', 'Demande', 'Transfert'] },
  { key: 'landedCostAutomation', title: 'Queue automatisation landed cost', domain: 'Import', route: '/enterprise-automation/landed-cost-automation-queue-page', description: 'Queue landed cost avec DUM, fret, droits, base allocation et aperçu comptable.', metrics: [{ label: 'DUM', path: 'rows', format: 'count' }, { label: 'Fret', path: 'rows.0.freight', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['DUM', 'Fret', 'Droits', 'Comptabilité'] },
  { key: 'fxRevaluation', title: 'Dashboard réévaluation devises', domain: 'Trésorerie', route: '/enterprise-automation/foreign-currency-revaluation-dashboard-page', description: 'Réévaluation devises avec devise, solde ouvert, cours clôture, gain/perte et journal.', metrics: [{ label: 'Devises', path: 'rows', format: 'count' }, { label: 'Gain/perte', path: 'rows.0.unrealizedGainLoss', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Devise', 'Solde', 'Cours', 'Journal'] },
  { key: 'recurringInvoiceMonitor', title: 'Monitor factures récurrentes', domain: 'Facturation', route: '/enterprise-automation/recurring-invoice-automation-monitor-page', description: 'Monitor automation factures récurrentes avec contrat, next run, échec, revenu et retry owner.', metrics: [{ label: 'Batches', path: 'rows', format: 'count' }, { label: 'Revenu', path: 'rows.0.revenue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Contrat', 'Next run', 'Échec', 'Retry'] },
  { key: 'usageBillingAudit', title: 'Audit facturation usage SaaS', domain: 'SaaS', route: '/enterprise-automation/subscription-usage-billing-audit-page', description: 'Audit usage billing avec quota inclus, usage réel, overage et impact facture.', metrics: [{ label: 'Usage', path: 'actualUsage' }, { label: 'Overage', path: 'overage' }, { label: 'Statut', path: 'status' }], controls: ['Quota', 'Usage', 'Overage', 'Facture'] },
  { key: 'tenantHealthForecast', title: 'Prévision incidents santé tenant', domain: 'SaaS', route: '/enterprise-automation/tenant-health-incident-forecast-page', description: 'Forecast santé tenant avec adoption, support load, billing, blockers conformité et risque.', metrics: [{ label: 'Support', path: 'supportLoad' }, { label: 'Risque', path: 'riskLevel' }, { label: 'Statut', path: 'status' }], controls: ['Adoption', 'Support', 'Billing', 'Conformité'] },
  { key: 'migrationReadiness', title: 'Readiness migration implémentation', domain: 'Migration', route: '/enterprise-automation/implementation-migration-readiness-page', description: 'Readiness migration avec système source, entités mappées, erreurs validation et cutover.', metrics: [{ label: 'Entités', path: 'mappedEntities', format: 'count' }, { label: 'Erreurs', path: 'validationErrors' }, { label: 'Statut', path: 'status' }], controls: ['Source', 'Mapping', 'Validation', 'Cutover'] },
  { key: 'releaseImpactSimulator', title: 'Simulateur impact release', domain: 'Plateforme', route: '/enterprise-automation/release-impact-simulator-page', description: 'Simulation impact release avec module, tenants affectés, risque migration, rollback et support.', metrics: [{ label: 'Tenants', path: 'tenantsAffected' }, { label: 'Risque', path: 'migrationRisk' }, { label: 'Statut', path: 'status' }], controls: ['Module', 'Migration', 'Rollback', 'Support'] },
  { key: 'accessReviewCampaign', title: 'Campagne revue accès sécurité', domain: 'Sécurité', route: '/enterprise-automation/security-access-review-campaign-page', description: 'Campagne revue accès avec rôles, utilisateurs inactifs, privilèges, reviewer et révocation.', metrics: [{ label: 'Utilisateurs', path: 'rows', format: 'count' }, { label: 'Privilèges', path: 'rows.0.privilegedPermissions' }, { label: 'Statut', path: 'status' }], controls: ['Rôle', 'Inactivité', 'Privilège', 'Révocation'] },
  { key: 'apiKeyRotationCampaign', title: 'Campagne rotation clés API', domain: 'Intégrations', route: '/enterprise-automation/api-key-rotation-campaign-page', description: 'Rotation clés API partenaires avec scopes, âge, expiry, owner et statut rotation.', metrics: [{ label: 'Clés', path: 'rows', format: 'count' }, { label: 'Âge', path: 'rows.0.age' }, { label: 'Statut', path: 'status' }], controls: ['Partenaire', 'Scopes', 'Expiry', 'Rotation'] },
  { key: 'webhookContractTesting', title: 'Dashboard tests contrats webhooks', domain: 'Intégrations', route: '/enterprise-automation/webhook-contract-testing-dashboard-page', description: 'Tests contrats webhooks avec event, version schema, statut consumer, échecs et replay.', metrics: [{ label: 'Events', path: 'rows', format: 'count' }, { label: 'Échecs', path: 'rows.0.failures' }, { label: 'Statut', path: 'status' }], controls: ['Event', 'Schema', 'Consumer', 'Replay'] },
  { key: 'biExportCatalog', title: 'Catalogue exports BI', domain: 'BI', route: '/enterprise-automation/bi-export-catalog-page', description: 'Catalogue BI avec dataset, champs, cadence refresh, base légale et approbation.', metrics: [{ label: 'Datasets', path: 'rows', format: 'count' }, { label: 'Cadence', path: 'rows.0.refreshCadence' }, { label: 'Statut', path: 'status' }], controls: ['Dataset', 'Champs', 'Cadence', 'Approbation'] },
];

export const enterpriseAutomationFeatureByKey = Object.fromEntries(
  enterpriseAutomationFeatureDefinitions.map((definition) => [definition.key, definition]),
) as Record<EnterpriseAutomationFeatureKey, EnterpriseAutomationFeatureDefinition>;
