export type EnterpriseResilienceFeatureKey =
  | 'businessContinuityCenter'
  | 'incidentEscalationBoard'
  | 'disasterRecoveryEvidence'
  | 'legalHoldRegister'
  | 'dataSubjectRequestQueue'
  | 'vendorSanctionsScreening'
  | 'procurementContractCompliance'
  | 'purchasePriceExceptions'
  | 'stockWriteOffQueue'
  | 'inventoryInsuranceExposure'
  | 'expiryColdChainRisk'
  | 'eInvoiceRolloutReadiness'
  | 'disputeReserveForecast'
  | 'badDebtProvisionReview'
  | 'cashConcentrationPlanner'
  | 'bankFeeAnomalyReview'
  | 'leaveAccrualProvisioning'
  | 'employeePrivacyAccessAudit'
  | 'healthSafetyIncidentTracker'
  | 'workforceCapacityRota'
  | 'posRefundAuthorization'
  | 'ecommercePayoutEvidence'
  | 'branchOpeningCompliance'
  | 'fleetFuelFraudControls'
  | 'maintenanceDowntimeSla'
  | 'productionBatchCosting'
  | 'qualityCertificateVault'
  | 'projectDeliverableAcceptance'
  | 'servicePenaltyEscalations'
  | 'customerPortalAccessReview'
  | 'supplierPortalSecurityReview'
  | 'apiConsentLedger'
  | 'webhookDeadLetterQueue'
  | 'dataWarehouseExportApproval'
  | 'biKpiCatalog'
  | 'aiSuggestionGovernance'
  | 'accountantEvidenceSla'
  | 'taxAuditReadinessBinder'
  | 'boardPackFinancialControls'
  | 'executiveResilienceScorecard';

export type EnterpriseResilienceMetric = { label: string; path: string; format?: 'money' | 'count' | 'boolean' };

export type EnterpriseResilienceFeatureDefinition = {
  key: EnterpriseResilienceFeatureKey;
  title: string;
  domain: string;
  route: string;
  description: string;
  metrics: EnterpriseResilienceMetric[];
  controls: string[];
};

export const enterpriseResilienceFeatureDefinitions: EnterpriseResilienceFeatureDefinition[] = [
  { key: 'businessContinuityCenter', title: 'Centre continuité activité', domain: 'Résilience', route: '/enterprise-resilience/business-continuity-command-center-page', description: 'Centre de continuité avec processus, RTO, RPO, dépendance, owner et statut exercice.', metrics: [{ label: 'Processus', path: 'rows', format: 'count' }, { label: 'RTO', path: 'rows.0.rtoHours' }, { label: 'Statut', path: 'status' }], controls: ['Processus', 'RTO', 'RPO', 'Exercice'] },
  { key: 'incidentEscalationBoard', title: 'Board escalade incidents', domain: 'Incidents', route: '/enterprise-resilience/incident-escalation-board-page', description: 'Escalade incidents avec type, sévérité, source détection, owner et timer SLA.', metrics: [{ label: 'Incidents', path: 'rows', format: 'count' }, { label: 'Sévérité', path: 'rows.0.severity' }, { label: 'Statut', path: 'status' }], controls: ['Type', 'Sévérité', 'Source', 'SLA'] },
  { key: 'disasterRecoveryEvidence', title: 'Pack preuves disaster recovery', domain: 'Résilience', route: '/enterprise-resilience/disaster-recovery-evidence-pack-page', description: 'Preuves DR avec backup set, test restore, checksum, owner et readiness.', metrics: [{ label: 'Preuves', path: 'rows', format: 'count' }, { label: 'Readiness', path: 'rows.0.readiness' }, { label: 'Statut', path: 'status' }], controls: ['Backup', 'Restore', 'Checksum', 'Owner'] },
  { key: 'legalHoldRegister', title: 'Registre legal hold', domain: 'Juridique', route: '/enterprise-resilience/legal-hold-case-register-page', description: 'Registre legal hold avec cas, dataset, raison, reviewer et statut release.', metrics: [{ label: 'Cas', path: 'rows', format: 'count' }, { label: 'Dataset', path: 'rows.0.affectedDataset' }, { label: 'Statut', path: 'status' }], controls: ['Cas', 'Dataset', 'Raison', 'Release'] },
  { key: 'dataSubjectRequestQueue', title: 'Queue demandes données clients', domain: 'Données', route: '/enterprise-resilience/customer-data-subject-request-queue-page', description: 'Queue demandes données avec demandeur, canal, échéance, périmètre et statut.', metrics: [{ label: 'Demandes', path: 'rows', format: 'count' }, { label: 'Canal', path: 'rows.0.channel' }, { label: 'Statut', path: 'status' }], controls: ['Demandeur', 'Canal', 'Échéance', 'Action'] },
  { key: 'vendorSanctionsScreening', title: 'Screening sanctions fournisseurs', domain: 'Tiers', route: '/enterprise-resilience/vendor-sanctions-screening-page', description: 'Screening fournisseurs avec ICE, pays, résultat et owner revue.', metrics: [{ label: 'Fournisseurs', path: 'rows', format: 'count' }, { label: 'Résultat', path: 'rows.0.screeningResult' }, { label: 'Statut', path: 'status' }], controls: ['Fournisseur', 'ICE', 'Pays', 'Revue'] },
  { key: 'procurementContractCompliance', title: 'Conformité contrats achats', domain: 'Achats', route: '/enterprise-resilience/procurement-contract-compliance-board-page', description: 'Contrats achats avec clause, renouvellement, exposition spend et blocker.', metrics: [{ label: 'Contrats', path: 'rows', format: 'count' }, { label: 'Exposition', path: 'rows.0.spendExposure', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Contrat', 'Clause', 'Renouvellement', 'Blocker'] },
  { key: 'purchasePriceExceptions', title: 'Exceptions approbation prix achat', domain: 'Achats', route: '/enterprise-resilience/purchase-price-approval-exceptions-page', description: 'Exceptions prix achat avec item, fournisseur, variance, seuil et approver.', metrics: [{ label: 'Exceptions', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.variance' }, { label: 'Statut', path: 'status' }], controls: ['Item', 'Fournisseur', 'Variance', 'Approver'] },
  { key: 'stockWriteOffQueue', title: 'Queue autorisation write-off stock', domain: 'Stock', route: '/enterprise-resilience/stock-write-off-authorization-queue-page', description: 'Write-off stock avec SKU, dépôt, raison, valeur et chemin approbation.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Valeur', path: 'rows.0.value', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['SKU', 'Dépôt', 'Raison', 'Approbation'] },
  { key: 'inventoryInsuranceExposure', title: 'Exposition assurance stock', domain: 'Stock', route: '/enterprise-resilience/inventory-insurance-exposure-report-page', description: 'Exposition assurance inventaire avec dépôt, valeur stock, cap couverture, gap et action.', metrics: [{ label: 'Dépôts', path: 'rows', format: 'count' }, { label: 'Gap', path: 'rows.0.gap', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Dépôt', 'Valeur', 'Cap', 'Action'] },
  { key: 'expiryColdChainRisk', title: 'Risque expiration et chaîne froide', domain: 'Qualité', route: '/enterprise-resilience/expiry-cold-chain-risk-board-page', description: 'Risque expiration avec produit, lot, date, température et disposition.', metrics: [{ label: 'Lots', path: 'rows', format: 'count' }, { label: 'Disposition', path: 'rows.0.disposition' }, { label: 'Statut', path: 'status' }], controls: ['Produit', 'Lot', 'Expiration', 'Température'] },
  { key: 'eInvoiceRolloutReadiness', title: 'Readiness rollout e-facture', domain: 'Fiscalité', route: '/enterprise-resilience/e-invoice-rollout-readiness-controls-page', description: 'Readiness e-facture avec série, mentions légales, mode adaptateur et blockers.', metrics: [{ label: 'Série', path: 'invoiceSeries' }, { label: 'Blockers', path: 'blockers', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Série', 'Mentions', 'Adaptateur', 'Blockers'] },
  { key: 'disputeReserveForecast', title: 'Forecast réserve litiges clients', domain: 'Finance', route: '/enterprise-resilience/customer-dispute-reserve-forecast-page', description: 'Réserve litiges avec client, montant contesté, probabilité, provision et revue.', metrics: [{ label: 'Litiges', path: 'rows', format: 'count' }, { label: 'Réserve', path: 'rows.0.reserve', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Montant', 'Probabilité', 'Réserve'] },
  { key: 'badDebtProvisionReview', title: 'Revue provision créances douteuses', domain: 'Finance', route: '/enterprise-resilience/bad-debt-provision-review-page', description: 'Provision créances avec aging, exposition, taux provision et preview journal.', metrics: [{ label: 'Créances', path: 'rows', format: 'count' }, { label: 'Exposition', path: 'rows.0.exposure', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Aging', 'Exposition', 'Journal'] },
  { key: 'cashConcentrationPlanner', title: 'Planner concentration cash', domain: 'Trésorerie', route: '/enterprise-resilience/cash-concentration-transfer-planner-page', description: 'Concentration cash avec compte source, cible, balance, seuil et proposition.', metrics: [{ label: 'Comptes', path: 'rows', format: 'count' }, { label: 'Proposition', path: 'rows.0.proposal', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Source', 'Cible', 'Balance', 'Seuil'] },
  { key: 'bankFeeAnomalyReview', title: 'Revue anomalies frais bancaires', domain: 'Banque', route: '/enterprise-resilience/bank-fee-anomaly-review-page', description: 'Anomalies frais banque avec type frais, attendu, facturé et résolution.', metrics: [{ label: 'Frais', path: 'rows', format: 'count' }, { label: 'Facturé', path: 'rows.0.chargedFee', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Banque', 'Type', 'Attendu', 'Résolution'] },
  { key: 'leaveAccrualProvisioning', title: 'Provision congés paie', domain: 'Paie', route: '/enterprise-resilience/payroll-leave-accrual-provisioning-page', description: 'Provision congés avec salarié, solde, taux journalier, provision et période.', metrics: [{ label: 'Salariés', path: 'rows', format: 'count' }, { label: 'Provision', path: 'rows.0.provision', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Salarié', 'Solde', 'Taux', 'Période'] },
  { key: 'employeePrivacyAccessAudit', title: 'Audit accès documents salariés', domain: 'RH', route: '/enterprise-resilience/employee-document-privacy-access-audit-page', description: 'Audit confidentialité RH avec document, rôle, raison accès et redaction.', metrics: [{ label: 'Accès', path: 'rows', format: 'count' }, { label: 'Redaction', path: 'rows.0.redactionStatus' }, { label: 'Statut', path: 'status' }], controls: ['Salarié', 'Document', 'Rôle', 'Redaction'] },
  { key: 'healthSafetyIncidentTracker', title: 'Tracker incidents santé sécurité', domain: 'HSE', route: '/enterprise-resilience/health-and-safety-incident-tracker-page', description: 'Incidents HSE avec site, incident, sévérité, action corrective et preuve.', metrics: [{ label: 'Incidents', path: 'rows', format: 'count' }, { label: 'Sévérité', path: 'rows.0.severity' }, { label: 'Statut', path: 'status' }], controls: ['Site', 'Incident', 'Action', 'Preuve'] },
  { key: 'workforceCapacityRota', title: 'Planner rota capacité workforce', domain: 'RH', route: '/enterprise-resilience/workforce-capacity-rota-planner-page', description: 'Capacité workforce avec équipe, heures planifiées, disponibles, gap et mitigation.', metrics: [{ label: 'Équipes', path: 'rows', format: 'count' }, { label: 'Gap', path: 'rows.0.gap' }, { label: 'Statut', path: 'status' }], controls: ['Équipe', 'Planifié', 'Disponible', 'Mitigation'] },
  { key: 'posRefundAuthorization', title: 'Matrice autorisation remboursements POS', domain: 'POS', route: '/enterprise-resilience/pos-refund-authorization-matrix-page', description: 'Matrice remboursement POS avec caissier, montant, raison, rôle requis et résultat.', metrics: [{ label: 'Remboursements', path: 'rows', format: 'count' }, { label: 'Rôle', path: 'rows.0.roleRequired' }, { label: 'Statut', path: 'status' }], controls: ['Caissier', 'Montant', 'Raison', 'Rôle'] },
  { key: 'ecommercePayoutEvidence', title: 'Preuves rapprochement payouts e-commerce', domain: 'E-commerce', route: '/enterprise-resilience/ecommerce-payout-reconciliation-evidence-page', description: 'Payout e-commerce avec marketplace, payout, commandes matchées, variance et archive.', metrics: [{ label: 'Payouts', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.variance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Marketplace', 'Payout', 'Commandes', 'Archive'] },
  { key: 'branchOpeningCompliance', title: 'Checklist conformité ouverture agence', domain: 'Agences', route: '/enterprise-resilience/branch-opening-compliance-checklist-page', description: 'Ouverture agence avec ville, bail, fiscalité, staffing et blocker.', metrics: [{ label: 'Agences', path: 'rows', format: 'count' }, { label: 'Blocker', path: 'rows.0.launchBlocker' }, { label: 'Statut', path: 'status' }], controls: ['Ville', 'Bail', 'Fiscalité', 'Staffing'] },
  { key: 'fleetFuelFraudControls', title: 'Contrôles fraude carburant flotte', domain: 'Flotte', route: '/enterprise-resilience/fleet-fuel-fraud-controls-page', description: 'Contrôles carburant avec véhicule, chauffeur, dépense, kilométrage, score et action.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Score', path: 'rows.0.anomalyScore' }, { label: 'Statut', path: 'status' }], controls: ['Véhicule', 'Chauffeur', 'Carburant', 'Action'] },
  { key: 'maintenanceDowntimeSla', title: 'Dashboard SLA downtime maintenance', domain: 'Maintenance', route: '/enterprise-resilience/maintenance-downtime-sla-dashboard-page', description: 'SLA downtime avec actif, work order, downtime, breach et owner.', metrics: [{ label: 'Work orders', path: 'rows', format: 'count' }, { label: 'Downtime', path: 'rows.0.downtime' }, { label: 'Statut', path: 'status' }], controls: ['Actif', 'WO', 'Downtime', 'Owner'] },
  { key: 'productionBatchCosting', title: 'Audit costing batch production', domain: 'Production', route: '/enterprise-resilience/production-batch-costing-audit-page', description: 'Costing production avec ordre, matières, main-d’œuvre, overhead, variance et reviewer.', metrics: [{ label: 'Ordres', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.variance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Ordre', 'Matières', 'Overhead', 'Reviewer'] },
  { key: 'qualityCertificateVault', title: 'Coffre certificats qualité', domain: 'Qualité', route: '/enterprise-resilience/quality-certificate-evidence-vault-page', description: 'Coffre certificats avec fournisseur, certificat, expiration, lots liés et statut.', metrics: [{ label: 'Certificats', path: 'rows', format: 'count' }, { label: 'Statut approbation', path: 'rows.0.approvalStatus' }, { label: 'Statut', path: 'status' }], controls: ['Fournisseur', 'Certificat', 'Lots', 'Statut'] },
  { key: 'projectDeliverableAcceptance', title: 'Acceptation livrables projet', domain: 'Projets', route: '/enterprise-resilience/project-contract-deliverable-acceptance-page', description: 'Acceptation livrables avec projet, livrable, sign-off client, impact facturation et risque.', metrics: [{ label: 'Livrables', path: 'rows', format: 'count' }, { label: 'Impact', path: 'rows.0.billingImpact', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Projet', 'Livrable', 'Sign-off', 'Risque'] },
  { key: 'servicePenaltyEscalations', title: 'Pénalités escalade contrats service', domain: 'Service', route: '/enterprise-resilience/service-contract-escalation-penalties-page', description: 'Pénalités service avec contrat, breach SLA, estimation, owner et plan recovery.', metrics: [{ label: 'Contrats', path: 'rows', format: 'count' }, { label: 'Pénalité', path: 'rows.0.penaltyEstimate', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Contrat', 'SLA', 'Pénalité', 'Recovery'] },
  { key: 'customerPortalAccessReview', title: 'Revue accès portail client', domain: 'Portails', route: '/enterprise-resilience/customer-portal-access-review-page', description: 'Revue portail client avec utilisateurs, dernier login, risque permission et révocation.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Risque', path: 'rows.0.permissionRisk' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Users', 'Login', 'Révocation'] },
  { key: 'supplierPortalSecurityReview', title: 'Revue sécurité portail fournisseur', domain: 'Portails', route: '/enterprise-resilience/supplier-portal-security-review-page', description: 'Revue portail fournisseur avec users, accès documents, comptes stale et remediation.', metrics: [{ label: 'Fournisseurs', path: 'rows', format: 'count' }, { label: 'Remediation', path: 'rows.0.remediation' }, { label: 'Statut', path: 'status' }], controls: ['Fournisseur', 'Users', 'Documents', 'Remediation'] },
  { key: 'apiConsentLedger', title: 'Ledger consentements API', domain: 'Intégrations', route: '/enterprise-resilience/api-consent-ledger-page', description: 'Ledger API avec client, scope, base légale, expiration et owner renouvellement.', metrics: [{ label: 'Clients API', path: 'rows', format: 'count' }, { label: 'Base légale', path: 'rows.0.legalBasis' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Scope', 'Base légale', 'Expiration'] },
  { key: 'webhookDeadLetterQueue', title: 'Queue dead-letter webhooks', domain: 'Intégrations', route: '/enterprise-resilience/webhook-dead-letter-queue-page', description: 'Dead-letter webhooks avec event, target, tentatives, erreur et décision replay.', metrics: [{ label: 'Events', path: 'rows', format: 'count' }, { label: 'Décision', path: 'rows.0.replayDecision' }, { label: 'Statut', path: 'status' }], controls: ['Event', 'Target', 'Erreur', 'Replay'] },
  { key: 'dataWarehouseExportApproval', title: 'Approbation exports data warehouse', domain: 'Data', route: '/enterprise-resilience/data-warehouse-export-approval-page', description: 'Exports DWH avec dataset, champs, base légale, approver et statut export.', metrics: [{ label: 'Datasets', path: 'rows', format: 'count' }, { label: 'Export', path: 'rows.0.exportStatus' }, { label: 'Statut', path: 'status' }], controls: ['Dataset', 'Champs', 'Base légale', 'Approver'] },
  { key: 'biKpiCatalog', title: 'Catalogue définitions KPI BI', domain: 'BI', route: '/enterprise-resilience/bi-kpi-definition-catalog-page', description: 'Catalogue KPI avec formule, owner, dataset source et validation.', metrics: [{ label: 'KPI', path: 'rows', format: 'count' }, { label: 'Validation', path: 'rows.0.validationStatus' }, { label: 'Statut', path: 'status' }], controls: ['KPI', 'Formule', 'Source', 'Validation'] },
  { key: 'aiSuggestionGovernance', title: 'Queue gouvernance suggestions IA', domain: 'Gouvernance', route: '/enterprise-resilience/ai-suggestion-governance-queue-page', description: 'Gouvernance suggestions avec type, module source, confiance, reviewer et décision.', metrics: [{ label: 'Suggestions', path: 'rows', format: 'count' }, { label: 'Confiance', path: 'rows.0.confidence' }, { label: 'Statut', path: 'status' }], controls: ['Type', 'Module', 'Confiance', 'Décision'] },
  { key: 'accountantEvidenceSla', title: 'SLA demandes preuves comptable', domain: 'Comptable', route: '/enterprise-resilience/accountant-evidence-request-sla-page', description: 'SLA preuves comptable avec client, requête, âge, échéance, escalation et statut.', metrics: [{ label: 'Demandes', path: 'rows', format: 'count' }, { label: 'Escalade', path: 'rows.0.escalation' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Requête', 'Échéance', 'Evidence'] },
  { key: 'taxAuditReadinessBinder', title: 'Binder readiness audit fiscal', domain: 'Fiscalité', route: '/enterprise-resilience/tax-audit-readiness-binder-page', description: 'Binder audit fiscal avec section, preuve requise, checksum, reviewer et gap.', metrics: [{ label: 'Sections', path: 'rows', format: 'count' }, { label: 'Gap', path: 'rows.0.gap', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Section', 'Preuve', 'Checksum', 'Gap'] },
  { key: 'boardPackFinancialControls', title: 'Contrôles board pack financier', domain: 'Direction', route: '/enterprise-resilience/board-pack-financial-controls-page', description: 'Board pack financier avec rapport, période, préparateur, reviewer et sign-off.', metrics: [{ label: 'Rapports', path: 'rows', format: 'count' }, { label: 'Sign-off', path: 'rows.0.signOffStatus' }, { label: 'Statut', path: 'status' }], controls: ['Rapport', 'Période', 'Préparateur', 'Sign-off'] },
  { key: 'executiveResilienceScorecard', title: 'Scorecard résilience direction', domain: 'Direction', route: '/enterprise-resilience/executive-resilience-scorecard-page', description: 'Scorecard direction avec continuité, incidents, gaps preuves, blockers et prochaine action.', metrics: [{ label: 'Score', path: 'continuityScore' }, { label: 'Incidents', path: 'openIncidents' }, { label: 'Blockers', path: 'complianceBlockers' }], controls: ['Continuité', 'Incidents', 'Preuves', 'Action'] },
];

export const enterpriseResilienceFeatureByKey = Object.fromEntries(
  enterpriseResilienceFeatureDefinitions.map((definition) => [definition.key, definition]),
) as Record<EnterpriseResilienceFeatureKey, EnterpriseResilienceFeatureDefinition>;
