export type EnterpriseIntelligenceFeatureKey =
  | 'salesPipelineForecast'
  | 'customerLifetimeValue'
  | 'renewalRevenueCalendar'
  | 'pricingElasticity'
  | 'dsoForecast'
  | 'supplierPriceVariance'
  | 'purchaseBudgetBurn'
  | 'stockServiceLevel'
  | 'demandForecast'
  | 'warehouseSlotting'
  | 'productionYield'
  | 'qualityNonconformance'
  | 'fleetCo2Fuel'
  | 'maintenanceCostTrend'
  | 'projectMilestoneBillingRisk'
  | 'consultantStaffingForecast'
  | 'payrollOvertimeRisk'
  | 'leaveLiability'
  | 'trainingRoi'
  | 'cnssDueReminder'
  | 'vatSensitivity'
  | 'iceIfDataQuality'
  | 'auditSampling'
  | 'bankCovenant'
  | 'cashRunway'
  | 'creditInsurance'
  | 'ecommerceReturnReasons'
  | 'posFraudAnomaly'
  | 'loyaltyCohorts'
  | 'supportDeflectionKb'
  | 'onboardingTimeToValue'
  | 'featureEntitlementAudit'
  | 'apiErrorBudget'
  | 'webhookDeliverySlo'
  | 'dataRetentionPurge'
  | 'backupRestoreSla'
  | 'regionalProfitability'
  | 'branchExpansionReadiness'
  | 'partnerReferralPipeline'
  | 'accountantWorkloadBalancing';

export type EnterpriseIntelligenceMetric = { label: string; path: string; format?: 'money' | 'count' | 'boolean' };

export type EnterpriseIntelligenceFeatureDefinition = {
  key: EnterpriseIntelligenceFeatureKey;
  title: string;
  domain: string;
  route: string;
  description: string;
  metrics: EnterpriseIntelligenceMetric[];
  controls: string[];
};

export const enterpriseIntelligenceFeatureDefinitions: EnterpriseIntelligenceFeatureDefinition[] = [
  { key: 'salesPipelineForecast', title: 'Prévision pipeline ventes', domain: 'Ventes', route: '/enterprise-intelligence/sales-pipeline-forecast-page', description: 'Forecast pipeline avec leads pondérés, clôture attendue, impact TVA, owner et confiance.', metrics: [{ label: 'Pondéré', path: 'totalWeighted', format: 'money' }, { label: 'Leads', path: 'rows', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Leads', 'Date clôture', 'TVA', 'Confiance'] },
  { key: 'customerLifetimeValue', title: 'Valeur vie client', domain: 'CRM', route: '/enterprise-intelligence/customer-lifetime-value-dashboard-page', description: 'CLV client avec spend récurrent, marge, paiement, coût support et action rétention.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Marge', path: 'rows.0.margin', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Spend', 'Marge', 'Paiement', 'Rétention'] },
  { key: 'renewalRevenueCalendar', title: 'Calendrier renouvellements', domain: 'SaaS', route: '/enterprise-intelligence/renewal-revenue-calendar-page', description: 'Calendrier renouvellement avec contrat, date, préavis, uplift et owner.', metrics: [{ label: 'Renouvellements', path: 'rows', format: 'count' }, { label: 'Uplift', path: 'rows.0.uplift' }, { label: 'Statut', path: 'status' }], controls: ['Contrat', 'Préavis', 'Uplift', 'Owner'] },
  { key: 'pricingElasticity', title: 'Simulateur élasticité prix', domain: 'Pricing', route: '/enterprise-intelligence/pricing-elasticity-simulator-page', description: 'Simulation prix avec famille produit, remises, garde-fou marge, approbation et impact.', metrics: [{ label: 'Famille', path: 'productFamily' }, { label: 'Marge min', path: 'marginGuardrail' }, { label: 'Statut', path: 'status' }], controls: ['Produit', 'Remise', 'Marge', 'Approbation'] },
  { key: 'dsoForecast', title: 'Prévision DSO', domain: 'Recouvrement', route: '/enterprise-intelligence/dso-forecast-control-page', description: 'Contrôle DSO avec aging, promesses, litiges exclus, cible jours et escalation.', metrics: [{ label: 'DSO prévu', path: 'forecastDays' }, { label: 'Créances', path: 'receivablesAging', format: 'money' }, { label: 'Escalation', path: 'escalation' }], controls: ['Aging', 'Promesses', 'Litiges', 'Cible'] },
  { key: 'supplierPriceVariance', title: 'Variance prix fournisseur', domain: 'Achats', route: '/enterprise-intelligence/supplier-price-variance-monitor-page', description: 'Monitor variance fournisseur avec dernier achat, devis courant, seuil approbation et alternative.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.variance' }, { label: 'Statut', path: 'status' }], controls: ['Dernier achat', 'Devis', 'Seuil', 'Alternative'] },
  { key: 'purchaseBudgetBurn', title: 'Consommation budget achats', domain: 'Achats', route: '/enterprise-intelligence/purchase-budget-burn-dashboard-page', description: 'Budget achats avec département, commandes, réception, budget restant et blocker.', metrics: [{ label: 'Budget restant', path: 'remainingBudget', format: 'money' }, { label: 'Commandes', path: 'committedOrders', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Département', 'Commandé', 'Réceptionné', 'Budget'] },
  { key: 'stockServiceLevel', title: 'Niveau service stock', domain: 'Stock', route: '/enterprise-intelligence/stock-service-level-dashboard-page', description: 'Service level stock avec demande, disponible, seuil réappro, fill rate et owner rupture.', metrics: [{ label: 'Articles', path: 'rows', format: 'count' }, { label: 'Fill rate', path: 'rows.0.fillRate' }, { label: 'Statut', path: 'status' }], controls: ['Demande', 'Disponible', 'Réappro', 'Owner'] },
  { key: 'demandForecast', title: 'Revue prévision demande', domain: 'Stock', route: '/enterprise-intelligence/demand-forecast-review-page', description: 'Forecast demande avec historique ventes, saisonnalité, sécurité, PO suggéré et validation.', metrics: [{ label: 'Articles', path: 'rows', format: 'count' }, { label: 'PO suggéré', path: 'rows.0.suggestedPo' }, { label: 'Statut', path: 'status' }], controls: ['Historique', 'Saisonnalité', 'Sécurité', 'Validation'] },
  { key: 'warehouseSlotting', title: 'Optimisation slotting dépôt', domain: 'Stock', route: '/enterprise-intelligence/warehouse-slotting-optimizer-page', description: 'Slotting dépôt avec vélocité, zone bin, distance picking, réappro et move plan.', metrics: [{ label: 'Emplacements', path: 'rows', format: 'count' }, { label: 'Zone', path: 'rows.0.binZone' }, { label: 'Statut', path: 'status' }], controls: ['Vélocité', 'Zone', 'Picking', 'Move plan'] },
  { key: 'productionYield', title: 'Analytics rendement production', domain: 'Production', route: '/enterprise-intelligence/production-yield-analytics-page', description: 'Rendement production avec BOM, quantité, rebut, variance coût et owner correctif.', metrics: [{ label: 'Ordres', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.varianceCost', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['BOM', 'Produit', 'Rebut', 'Correctif'] },
  { key: 'qualityNonconformance', title: 'Non-conformité qualité', domain: 'Qualité', route: '/enterprise-intelligence/quality-nonconformance-workflow-page', description: 'Workflow NCR avec issue, batch affecté, containment, notices et CAPA.', metrics: [{ label: 'Issue', path: 'issueType' }, { label: 'Batch', path: 'affectedBatch' }, { label: 'Statut', path: 'status' }], controls: ['Issue', 'Batch', 'Containment', 'CAPA'] },
  { key: 'fleetCo2Fuel', title: 'CO2 et fuel flotte', domain: 'Flotte', route: '/enterprise-intelligence/fleet-co2-fuel-dashboard-page', description: 'Dashboard CO2 flotte avec véhicule, kilométrage, fuel, facteur émission et réduction.', metrics: [{ label: 'Véhicules', path: 'rows', format: 'count' }, { label: 'CO2', path: 'rows.0.co2Kg' }, { label: 'Statut', path: 'status' }], controls: ['Véhicule', 'Kilométrage', 'Fuel', 'Réduction'] },
  { key: 'maintenanceCostTrend', title: 'Tendance coût maintenance', domain: 'Maintenance', route: '/enterprise-intelligence/maintenance-cost-trend-page', description: 'Tendance maintenance par actif avec préventif, correctif, downtime et signal remplacement.', metrics: [{ label: 'Actifs', path: 'rows', format: 'count' }, { label: 'Correctif', path: 'rows.0.correctiveSpend', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Actif', 'Préventif', 'Correctif', 'Remplacement'] },
  { key: 'projectMilestoneBillingRisk', title: 'Risque facturation jalon', domain: 'Projets', route: '/enterprise-intelligence/project-milestone-billing-risk-page', description: 'Risque facturation projet avec jalon, preuve livrable, facture, retenue et owner retard.', metrics: [{ label: 'Jalon', path: 'milestone' }, { label: 'Retenue', path: 'retention' }, { label: 'Statut', path: 'status' }], controls: ['Jalon', 'Preuve', 'Facture', 'Retard'] },
  { key: 'consultantStaffingForecast', title: 'Prévision staffing consultants', domain: 'Services', route: '/enterprise-intelligence/consultant-staffing-forecast-page', description: 'Forecast staffing avec demande pipeline, capacité, rôle manquant, hiring et marge.', metrics: [{ label: 'Capacité', path: 'availableCapacity' }, { label: 'Impact marge', path: 'marginImpact', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Pipeline', 'Capacité', 'Rôle', 'Hiring'] },
  { key: 'payrollOvertimeRisk', title: 'Risque heures supplémentaires', domain: 'Paie', route: '/enterprise-intelligence/payroll-overtime-risk-forecast-page', description: 'Forecast overtime avec équipe, heures, cap légal, approbation et coût.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Coût', path: 'rows.0.costImpact', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Équipe', 'Heures', 'Cap', 'Coût'] },
  { key: 'leaveLiability', title: 'Passif congés', domain: 'RH', route: '/enterprise-intelligence/leave-liability-report-page', description: 'Report passif congés avec solde, taux journalier, passif, politique expiry et owner.', metrics: [{ label: 'Salariés', path: 'rows', format: 'count' }, { label: 'Passif', path: 'rows.0.liability', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Solde', 'Taux', 'Passif', 'Owner'] },
  { key: 'trainingRoi', title: 'ROI formation', domain: 'RH', route: '/enterprise-intelligence/training-roi-tracker-page', description: 'Tracker formation avec participants, coût, gain productivité, certificat et renouvellement.', metrics: [{ label: 'Formations', path: 'rows', format: 'count' }, { label: 'Coût', path: 'rows.0.cost', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Formation', 'Coût', 'Gain', 'Certificat'] },
  { key: 'cnssDueReminder', title: 'Rappel échéance CNSS', domain: 'Paie', route: '/enterprise-intelligence/cnss-due-reminder-page', description: 'Rappel CNSS avec période paie, déclaration, paiement, responsable et preuve.', metrics: [{ label: 'Période', path: 'payrollPeriod' }, { label: 'Responsable', path: 'responsibleUser' }, { label: 'Statut', path: 'status' }], controls: ['Période', 'Déclaration', 'Paiement', 'Preuve'] },
  { key: 'vatSensitivity', title: 'Analyse sensibilité TVA', domain: 'Fiscalité', route: '/enterprise-intelligence/vat-sensitivity-analysis-page', description: 'Sensibilité TVA avec ventes taxables, achats déductibles, exonéré, report crédit et cash.', metrics: [{ label: 'Scénario cash', path: 'cashScenario', format: 'money' }, { label: 'Ventes', path: 'taxableSales', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Ventes', 'Achats', 'Exonéré', 'Cash'] },
  { key: 'iceIfDataQuality', title: 'Qualité données ICE/IF', domain: 'Conformité', route: '/enterprise-intelligence/ice-if-data-quality-queue-page', description: 'Queue qualité ICE/IF avec tiers, champ manquant, document bloquant, owner et échéance.', metrics: [{ label: 'Anomalies', path: 'rows', format: 'count' }, { label: 'Champ', path: 'rows.0.missingField' }, { label: 'Statut', path: 'status' }], controls: ['Tiers', 'ICE/IF', 'Document', 'Owner'] },
  { key: 'auditSampling', title: 'Moteur échantillonnage audit', domain: 'Audit', route: '/enterprise-intelligence/audit-sampling-engine-page', description: 'Échantillonnage audit avec journal, score risque, écritures, preuve et reviewer.', metrics: [{ label: 'Sélection', path: 'selectedEntries' }, { label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Journal', 'Risque', 'Preuve', 'Reviewer'] },
  { key: 'bankCovenant', title: 'Monitor covenant bancaire', domain: 'Trésorerie', route: '/enterprise-intelligence/bank-covenant-monitor-page', description: 'Covenant bancaire avec solde, dette, ratio, seuil et alerte.', metrics: [{ label: 'Ratio', path: 'ratio' }, { label: 'Solde', path: 'bankBalance', format: 'money' }, { label: 'Alerte', path: 'alert' }], controls: ['Solde', 'Dette', 'Ratio', 'Alerte'] },
  { key: 'cashRunway', title: 'Runway trésorerie', domain: 'Trésorerie', route: '/enterprise-intelligence/cash-runway-dashboard-page', description: 'Runway cash avec solde, inflows, outflows, paie, TVA/IS et jours.', metrics: [{ label: 'Jours runway', path: 'runwayDays' }, { label: 'Solde', path: 'openingBalance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Solde', 'Entrées', 'Sorties', 'Fiscal'] },
  { key: 'creditInsurance', title: 'Registre assurance crédit', domain: 'Crédit', route: '/enterprise-intelligence/credit-insurance-register-page', description: 'Assurance crédit avec client, montant assuré, franchise, expiry, claim et preuve.', metrics: [{ label: 'Polices', path: 'rows', format: 'count' }, { label: 'Montant', path: 'rows.0.insuredAmount', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Montant', 'Franchise', 'Preuve'] },
  { key: 'ecommerceReturnReasons', title: 'Retours e-commerce', domain: 'Commerce', route: '/enterprise-intelligence/ecommerce-return-reason-analytics-page', description: 'Analytics retours e-commerce avec SKU, raison, remboursement, restock et action.', metrics: [{ label: 'SKU', path: 'rows', format: 'count' }, { label: 'Remboursement', path: 'rows.0.refundAmount', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['SKU', 'Raison', 'Restock', 'Action'] },
  { key: 'posFraudAnomaly', title: 'Anomalies fraude POS', domain: 'POS', route: '/enterprise-intelligence/pos-fraud-anomaly-dashboard-page', description: 'Anomalies POS avec caissier, annulations, remboursements, variance cash, shift et escalation.', metrics: [{ label: 'Sessions', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.cashVariance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Caissier', 'Remboursements', 'Variance', 'Escalation'] },
  { key: 'loyaltyCohorts', title: 'Cohortes fidélité', domain: 'Retail', route: '/enterprise-intelligence/loyalty-cohort-analytics-page', description: 'Cohorte fidélité avec mois, points gagnés, redemptions, breakage et passif.', metrics: [{ label: 'Passif', path: 'rows.0.liability', format: 'money' }, { label: 'Breakage', path: 'rows.0.breakage' }, { label: 'Statut', path: 'status' }], controls: ['Cohorte', 'Points', 'Redemption', 'Passif'] },
  { key: 'supportDeflectionKb', title: 'Déflexion support KB', domain: 'Support', route: '/enterprise-intelligence/support-deflection-knowledge-base-dashboard-page', description: 'Déflexion support avec thèmes tickets, couverture article, unresolved rate et owner.', metrics: [{ label: 'Thèmes', path: 'rows', format: 'count' }, { label: 'Couverture', path: 'rows.0.articleCoverage' }, { label: 'Statut', path: 'status' }], controls: ['Thèmes', 'Articles', 'Unresolved', 'Owner'] },
  { key: 'onboardingTimeToValue', title: 'Time-to-value onboarding', domain: 'Onboarding', route: '/enterprise-intelligence/onboarding-time-to-value-tracker-page', description: 'TTV onboarding avec tenant, milestones, jours, blocker et success manager.', metrics: [{ label: 'Jours', path: 'daysElapsed' }, { label: 'Blocker', path: 'blocker' }, { label: 'Statut', path: 'status' }], controls: ['Tenant', 'Milestones', 'Blocker', 'Manager'] },
  { key: 'featureEntitlementAudit', title: 'Audit droits fonctionnalités', domain: 'SaaS', route: '/enterprise-intelligence/feature-entitlement-audit-page', description: 'Audit entitlement avec plan, modules actifs, overage, risque downgrade et remediation.', metrics: [{ label: 'Modules', path: 'enabledModules', format: 'count' }, { label: 'Overage', path: 'overage' }, { label: 'Statut', path: 'status' }], controls: ['Plan', 'Modules', 'Overage', 'Remediation'] },
  { key: 'apiErrorBudget', title: 'Budget erreur API', domain: 'Plateforme', route: '/enterprise-intelligence/api-error-budget-dashboard-page', description: 'Error budget API avec endpoint, volume, failure rate, SLO et owner incident.', metrics: [{ label: 'Endpoints', path: 'rows', format: 'count' }, { label: 'Failure', path: 'rows.0.failureRate' }, { label: 'Statut', path: 'status' }], controls: ['Endpoint', 'Volume', 'SLO', 'Owner'] },
  { key: 'webhookDeliverySlo', title: 'SLO livraison webhook', domain: 'Intégrations', route: '/enterprise-intelligence/webhook-delivery-slo-dashboard-page', description: 'SLO webhook avec event type, latence, retry rate, targets en échec et replay.', metrics: [{ label: 'Events', path: 'rows', format: 'count' }, { label: 'Latence', path: 'rows.0.latency' }, { label: 'Statut', path: 'status' }], controls: ['Event', 'Latence', 'Retries', 'Replay'] },
  { key: 'dataRetentionPurge', title: 'Simulation purge rétention', domain: 'Sécurité', route: '/enterprise-intelligence/data-retention-purge-simulator-page', description: 'Simulation purge avec dataset, legal hold, deadline, count et approbation.', metrics: [{ label: 'Datasets', path: 'rows', format: 'count' }, { label: 'Rétention', path: 'retentionDays' }, { label: 'Statut', path: 'status' }], controls: ['Dataset', 'Legal hold', 'Deadline', 'Approbation'] },
  { key: 'backupRestoreSla', title: 'SLA backup restore', domain: 'Opérations', route: '/enterprise-intelligence/backup-restore-sla-dashboard-page', description: 'Dashboard SLA backup avec âge, test restore, RTO, RPO et preuve.', metrics: [{ label: 'RTO', path: 'rto' }, { label: 'RPO', path: 'rpo' }, { label: 'Statut', path: 'status' }], controls: ['Backup', 'Restore', 'RTO', 'Preuve'] },
  { key: 'regionalProfitability', title: 'Profitabilité régions Maroc', domain: 'Direction', route: '/enterprise-intelligence/moroccan-regional-profitability-dashboard-page', description: 'Profitabilité régionale avec région, revenu, marge, coût logistique et note fiscale.', metrics: [{ label: 'Régions', path: 'rows', format: 'count' }, { label: 'Revenu', path: 'rows.0.revenue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Région', 'Revenu', 'Marge', 'Fiscal'] },
  { key: 'branchExpansionReadiness', title: 'Readiness expansion agence', domain: 'Expansion', route: '/enterprise-intelligence/branch-expansion-readiness-page', description: 'Readiness agence avec ville, demande, staffing, documents légaux et checklist lancement.', metrics: [{ label: 'Villes', path: 'rows', format: 'count' }, { label: 'Agences', path: 'currentBranches' }, { label: 'Statut', path: 'status' }], controls: ['Ville', 'Demande', 'Staffing', 'Checklist'] },
  { key: 'partnerReferralPipeline', title: 'Pipeline referral partenaires', domain: 'Partenaires', route: '/enterprise-intelligence/partner-referral-pipeline-page', description: 'Referral partenaire avec partenaire, tenant référé, stage, MRR attendu et commission.', metrics: [{ label: 'Références', path: 'rows', format: 'count' }, { label: 'MRR', path: 'rows.0.expectedMrr', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Partenaire', 'Tenant', 'MRR', 'Commission'] },
  { key: 'accountantWorkloadBalancing', title: 'Équilibrage charge comptable', domain: 'Comptables', route: '/enterprise-intelligence/accountant-workload-balancing-page', description: 'Charge comptables avec clients, deadlines, blockers et proposition réassignation.', metrics: [{ label: 'Comptables', path: 'rows', format: 'count' }, { label: 'Clients', path: 'rows.0.clients' }, { label: 'Statut', path: 'status' }], controls: ['Comptable', 'Clients', 'Deadlines', 'Réassignation'] },
];

export const enterpriseIntelligenceFeatureByKey = Object.fromEntries(
  enterpriseIntelligenceFeatureDefinitions.map((definition) => [definition.key, definition]),
) as Record<EnterpriseIntelligenceFeatureKey, EnterpriseIntelligenceFeatureDefinition>;
