export type EnterpriseAssuranceFeatureKey =
  | 'dataResidencyEvidence'
  | 'privacyConsentAudit'
  | 'chartAccountAnomalyGuard'
  | 'journalDuplicateDetection'
  | 'fiscalLockImpact'
  | 'taxCalendarEvidenceSla'
  | 'cnssIdentityReadiness'
  | 'payrollBankApprovalQueue'
  | 'expensePolicyExceptions'
  | 'vendorDuplicateDetector'
  | 'customerDuplicateDetector'
  | 'productCompletenessScore'
  | 'warehouseCapacityHeatmap'
  | 'stockAgingLiquidation'
  | 'countVarianceApproval'
  | 'purchaseLeadTimeReliability'
  | 'supplierOnboardingRisk'
  | 'customerCreditRenewal'
  | 'quoteMarginApproval'
  | 'contractRenewalObligations'
  | 'deliveryPromiseAdherence'
  | 'returnsRootCause'
  | 'posCashierPerformance'
  | 'cashForecastVariance'
  | 'bankReconciliationAging'
  | 'assetInsuranceEvidence'
  | 'sparePartsAvailability'
  | 'fleetDocumentCompliance'
  | 'projectDeliveryRisk'
  | 'materialShortageBridge'
  | 'serviceTicketSlaHealth'
  | 'portalNotificationAudit'
  | 'apiUsageAnomaly'
  | 'webhookSchemaDrift'
  | 'backupEvidenceFreshness'
  | 'roleSegregationMatrix'
  | 'auditEvidenceRequests'
  | 'releaseRollbackChecklist'
  | 'configurationDriftMonitor'
  | 'executiveAssuranceDigest';

export type EnterpriseAssuranceMetric = { label: string; path: string; format?: 'money' | 'count' | 'boolean' };

export type EnterpriseAssuranceFeatureDefinition = {
  key: EnterpriseAssuranceFeatureKey;
  title: string;
  domain: string;
  route: string;
  description: string;
  metrics: EnterpriseAssuranceMetric[];
  controls: string[];
};

export const enterpriseAssuranceFeatureDefinitions: EnterpriseAssuranceFeatureDefinition[] = [
  { key: 'dataResidencyEvidence', title: 'Registre résidence des données', domain: 'Données', route: '/enterprise-assurance/data-residency-evidence-register-page', description: 'Registre résidence avec dataset, stockage, périmètre Maroc, owner légal et checksum.', metrics: [{ label: 'Datasets', path: 'rows', format: 'count' }, { label: 'Provider', path: 'rows.0.storageProvider' }, { label: 'Statut', path: 'status' }], controls: ['Dataset', 'Stockage', 'Maroc', 'Checksum'] },
  { key: 'privacyConsentAudit', title: 'Audit consentements confidentialité', domain: 'Données', route: '/enterprise-assurance/privacy-consent-audit-page', description: 'Audit consentements tiers avec langue, finalité, source collecte et rétention.', metrics: [{ label: 'Parties', path: 'rows', format: 'count' }, { label: 'Langue', path: 'rows.0.language' }, { label: 'Statut', path: 'status' }], controls: ['Partie', 'Langue', 'Finalité', 'Rétention'] },
  { key: 'chartAccountAnomalyGuard', title: 'Garde anomalies comptes PCGE', domain: 'Comptabilité', route: '/enterprise-assurance/chart-account-anomaly-guard-page', description: 'Contrôle comptes PCGE avec libellé, activité, risque et reviewer.', metrics: [{ label: 'Comptes', path: 'rows', format: 'count' }, { label: 'Activité', path: 'rows.0.activity' }, { label: 'Statut', path: 'status' }], controls: ['Compte', 'Libellé', 'Activité', 'Reviewer'] },
  { key: 'journalDuplicateDetection', title: 'Détection doublons écritures', domain: 'Comptabilité', route: '/enterprise-assurance/journal-duplicate-detection-page', description: 'Détection doublons journal avec date, source, fingerprint montant, risque et owner.', metrics: [{ label: 'Écritures', path: 'rows', format: 'count' }, { label: 'Risque', path: 'rows.0.duplicateRisk' }, { label: 'Statut', path: 'status' }], controls: ['Date', 'Source', 'Fingerprint', 'Résolution'] },
  { key: 'fiscalLockImpact', title: 'Impact verrou fiscal', domain: 'Fiscalité', route: '/enterprise-assurance/fiscal-lock-impact-preview-page', description: 'Prévisualisation impact verrou fiscal par période, modules affectés, drafts et exception.', metrics: [{ label: 'Périodes', path: 'rows', format: 'count' }, { label: 'Risque', path: 'rows.0.riskLevel' }, { label: 'Statut', path: 'status' }], controls: ['Période', 'Modules', 'Drafts', 'Exception'] },
  { key: 'taxCalendarEvidenceSla', title: 'SLA preuves calendrier fiscal', domain: 'Fiscalité', route: '/enterprise-assurance/tax-calendar-evidence-sla-page', description: 'SLA preuves fiscales avec déclaration, échéance, âge preuve, owner et escalation.', metrics: [{ label: 'Déclarations', path: 'rows', format: 'count' }, { label: 'Âge preuve', path: 'rows.0.evidenceAge' }, { label: 'Statut', path: 'status' }], controls: ['Déclaration', 'Échéance', 'Preuve', 'Escalade'] },
  { key: 'cnssIdentityReadiness', title: 'Readiness identité CNSS salariés', domain: 'Paie', route: '/enterprise-assurance/cnss-employee-identity-readiness-board-page', description: 'Board identité CNSS avec salarié, CIN, numéro CNSS, contrat et blocker.', metrics: [{ label: 'Salariés', path: 'rows', format: 'count' }, { label: 'Blocker', path: 'rows.0.blocker' }, { label: 'Statut', path: 'status' }], controls: ['Salarié', 'CIN', 'CNSS', 'Contrat'] },
  { key: 'payrollBankApprovalQueue', title: 'Queue approbation fichier banque paie', domain: 'Paie', route: '/enterprise-assurance/payroll-bank-file-approval-queue-page', description: 'Queue fichier banque paie avec run, effectif, net total, approver et release.', metrics: [{ label: 'Runs', path: 'rows', format: 'count' }, { label: 'Net total', path: 'rows.0.netTotal', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Run', 'Effectif', 'Net', 'Release'] },
  { key: 'expensePolicyExceptions', title: 'Exceptions politique dépenses', domain: 'Finance', route: '/enterprise-assurance/expense-policy-exception-monitor-page', description: 'Monitor exceptions dépenses avec claimant, catégorie, montant, règle et route décision.', metrics: [{ label: 'Exceptions', path: 'rows', format: 'count' }, { label: 'Montant', path: 'rows.0.amount', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Claimant', 'Catégorie', 'Règle', 'Décision'] },
  { key: 'vendorDuplicateDetector', title: 'Détecteur doublons fournisseurs', domain: 'Master data', route: '/enterprise-assurance/vendor-master-duplicate-detector-page', description: 'Détection doublons fournisseurs avec ICE, RIB, raison et proposition merge.', metrics: [{ label: 'Fournisseurs', path: 'rows', format: 'count' }, { label: 'Merge', path: 'rows.0.mergeProposal' }, { label: 'Statut', path: 'status' }], controls: ['Fournisseur', 'ICE', 'RIB', 'Merge'] },
  { key: 'customerDuplicateDetector', title: 'Détecteur doublons clients', domain: 'Master data', route: '/enterprise-assurance/customer-master-duplicate-detector-page', description: 'Détection doublons clients avec ICE, ville, raison et proposition merge.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Merge', path: 'rows.0.mergeProposal' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'ICE', 'Ville', 'Merge'] },
  { key: 'productCompletenessScore', title: 'Score complétude articles', domain: 'Master data', route: '/enterprise-assurance/product-master-completeness-score-page', description: 'Score master article avec SKU, code-barres, description arabe, TVA et score.', metrics: [{ label: 'Articles', path: 'rows', format: 'count' }, { label: 'Score', path: 'rows.0.score' }, { label: 'Statut', path: 'status' }], controls: ['SKU', 'Barcode', 'Arabe', 'TVA'] },
  { key: 'warehouseCapacityHeatmap', title: 'Heatmap capacité dépôts', domain: 'Stock', route: '/enterprise-assurance/warehouse-capacity-heatmap-page', description: 'Heatmap dépôt avec lignes stock, réservé, utilisation et action.', metrics: [{ label: 'Dépôts', path: 'rows', format: 'count' }, { label: 'Utilisation', path: 'rows.0.utilization' }, { label: 'Statut', path: 'status' }], controls: ['Dépôt', 'Stock', 'Réservé', 'Action'] },
  { key: 'stockAgingLiquidation', title: 'Plan liquidation stock âgé', domain: 'Stock', route: '/enterprise-assurance/stock-aging-liquidation-planner-page', description: 'Plan stock âgé avec SKU, bucket âge, quantité, valeur et action liquidation.', metrics: [{ label: 'Articles', path: 'rows', format: 'count' }, { label: 'Valeur', path: 'rows.0.value', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['SKU', 'Âge', 'Quantité', 'Liquidation'] },
  { key: 'countVarianceApproval', title: 'Board approbation écarts inventaire', domain: 'Stock', route: '/enterprise-assurance/inventory-count-variance-approval-board-page', description: 'Approbation écarts inventaire avec feuille, dépôt, valeur, approver et statut.', metrics: [{ label: 'Feuilles', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.varianceValue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Feuille', 'Dépôt', 'Variance', 'Approver'] },
  { key: 'purchaseLeadTimeReliability', title: 'Fiabilité délais achats', domain: 'Achats', route: '/enterprise-assurance/purchase-lead-time-reliability-dashboard-page', description: 'Fiabilité délais achats avec fournisseur, date attendue, performance, score retard et action.', metrics: [{ label: 'Commandes', path: 'rows', format: 'count' }, { label: 'Score retard', path: 'rows.0.delayScore' }, { label: 'Statut', path: 'status' }], controls: ['Fournisseur', 'Date', 'Performance', 'Action'] },
  { key: 'supplierOnboardingRisk', title: 'Pack risque onboarding fournisseur', domain: 'Achats', route: '/enterprise-assurance/supplier-onboarding-risk-pack-page', description: 'Pack risque fournisseur avec documents, banque, KYS et note risque.', metrics: [{ label: 'Fournisseurs', path: 'rows', format: 'count' }, { label: 'KYS', path: 'rows.0.kysStatus' }, { label: 'Statut', path: 'status' }], controls: ['Documents', 'Banque', 'KYS', 'Risque'] },
  { key: 'customerCreditRenewal', title: 'Campagne renouvellement crédit client', domain: 'Crédit', route: '/enterprise-assurance/customer-credit-renewal-campaign-page', description: 'Campagne crédit avec exposition, limite, date renouvellement et recommandation.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Exposition', path: 'rows.0.exposure', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Exposition', 'Limite', 'Recommandation'] },
  { key: 'quoteMarginApproval', title: 'Simulateur approbation marge devis', domain: 'Ventes', route: '/enterprise-assurance/quote-margin-approval-simulator-page', description: 'Simulation marge devis avec marge brute, remise, rôle requis et statut approbation.', metrics: [{ label: 'Devis', path: 'rows', format: 'count' }, { label: 'Marge', path: 'rows.0.grossMargin' }, { label: 'Statut', path: 'status' }], controls: ['Devis', 'Marge', 'Remise', 'Rôle'] },
  { key: 'contractRenewalObligations', title: 'Obligations renouvellement contrats', domain: 'Contrats', route: '/enterprise-assurance/contract-renewal-obligation-board-page', description: 'Board obligations contrats avec date renouvellement, fenêtre préavis, owner et statut.', metrics: [{ label: 'Contrats', path: 'rows', format: 'count' }, { label: 'Obligation', path: 'rows.0.obligationStatus' }, { label: 'Statut', path: 'status' }], controls: ['Contrat', 'Renouvellement', 'Préavis', 'Owner'] },
  { key: 'deliveryPromiseAdherence', title: 'Adhérence promesses livraison', domain: 'Livraison', route: '/enterprise-assurance/delivery-promise-adherence-monitor-page', description: 'Adhérence livraison avec BL, ville, date promise, route et breach.', metrics: [{ label: 'BL', path: 'rows', format: 'count' }, { label: 'Route', path: 'rows.0.routeStatus' }, { label: 'Statut', path: 'status' }], controls: ['BL', 'Ville', 'Promesse', 'Breach'] },
  { key: 'returnsRootCause', title: 'Causes racines retours', domain: 'Ventes', route: '/enterprise-assurance/returns-root-cause-board-page', description: 'Board retours avec avoir, article, raison, valeur et owner correctif.', metrics: [{ label: 'Avoirs', path: 'rows', format: 'count' }, { label: 'Valeur', path: 'rows.0.value', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Avoir', 'Produit', 'Raison', 'Owner'] },
  { key: 'posCashierPerformance', title: 'Scorecard performance caissiers', domain: 'POS', route: '/enterprise-assurance/pos-cashier-performance-scorecard-page', description: 'Scorecard caissier avec sessions, variance, paiements et coaching.', metrics: [{ label: 'Caissiers', path: 'rows', format: 'count' }, { label: 'Variance', path: 'rows.0.variance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Caissier', 'Sessions', 'Variance', 'Coaching'] },
  { key: 'cashForecastVariance', title: 'Variance forecast cash', domain: 'Trésorerie', route: '/enterprise-assurance/cash-forecast-variance-monitor-page', description: 'Forecast cash avec ouverture, inflow, outflow, variance et action.', metrics: [{ label: 'Cash', path: 'openingCash', format: 'money' }, { label: 'Variance', path: 'variance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Ouverture', 'Inflow', 'Outflow', 'Action'] },
  { key: 'bankReconciliationAging', title: 'Queue aging rapprochement banque', domain: 'Banque', route: '/enterprise-assurance/bank-reconciliation-aging-queue-page', description: 'Aging rapprochement banque avec compte, lignes non rapprochées, âge, solde et owner.', metrics: [{ label: 'Comptes', path: 'rows', format: 'count' }, { label: 'Solde', path: 'rows.0.balance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Compte', 'Lignes', 'Âge', 'Owner'] },
  { key: 'assetInsuranceEvidence', title: 'Preuves assurance immobilisations', domain: 'Actifs', route: '/enterprise-assurance/fixed-asset-insurance-evidence-board-page', description: 'Board assurance actifs avec police, renouvellement, couverture et owner.', metrics: [{ label: 'Actifs', path: 'rows', format: 'count' }, { label: 'Couverture', path: 'rows.0.coverageStatus' }, { label: 'Statut', path: 'status' }], controls: ['Actif', 'Police', 'Renouvellement', 'Owner'] },
  { key: 'sparePartsAvailability', title: 'Disponibilité pièces maintenance', domain: 'Maintenance', route: '/enterprise-assurance/maintenance-spare-parts-availability-page', description: 'Disponibilité pièces avec work order, pièce, quantité requise, couverture et blocker.', metrics: [{ label: 'Pièces', path: 'rows', format: 'count' }, { label: 'Couverture', path: 'rows.0.stockCoverage' }, { label: 'Statut', path: 'status' }], controls: ['WO', 'Pièce', 'Quantité', 'Blocker'] },
  { key: 'fleetDocumentCompliance', title: 'Score conformité documents flotte', domain: 'Flotte', route: '/enterprise-assurance/fleet-document-compliance-score-page', description: 'Score documents flotte avec véhicule, document, échéance, preuve et score.', metrics: [{ label: 'Véhicules', path: 'rows', format: 'count' }, { label: 'Score', path: 'rows.0.score' }, { label: 'Statut', path: 'status' }], controls: ['Véhicule', 'Document', 'Échéance', 'Preuve'] },
  { key: 'projectDeliveryRisk', title: 'Radar risque livraison projet', domain: 'Projets', route: '/enterprise-assurance/project-delivery-risk-radar-page', description: 'Radar projet avec burn budget, facturation, charge timesheet et signal risque.', metrics: [{ label: 'Projets', path: 'rows', format: 'count' }, { label: 'Risque', path: 'rows.0.riskSignal' }, { label: 'Statut', path: 'status' }], controls: ['Budget', 'Facturation', 'Timesheets', 'Signal'] },
  { key: 'materialShortageBridge', title: 'Bridge pénuries matières production', domain: 'Production', route: '/enterprise-assurance/production-material-shortage-bridge-page', description: 'Bridge pénuries production avec ordre, composant, besoin, stock disponible et décision.', metrics: [{ label: 'Composants', path: 'rows', format: 'count' }, { label: 'Décision', path: 'rows.0.decision' }, { label: 'Statut', path: 'status' }], controls: ['Ordre', 'Composant', 'Besoin', 'Décision'] },
  { key: 'serviceTicketSlaHealth', title: 'Santé SLA tickets service', domain: 'Support', route: '/enterprise-assurance/service-ticket-sla-health-board-page', description: 'Santé SLA tickets avec sévérité, due time, statut et escalade.', metrics: [{ label: 'Tickets', path: 'rows', format: 'count' }, { label: 'Escalade', path: 'rows.0.escalation' }, { label: 'Statut', path: 'status' }], controls: ['Ticket', 'Sévérité', 'Due', 'Escalade'] },
  { key: 'portalNotificationAudit', title: 'Audit notifications portail', domain: 'Portails', route: '/enterprise-assurance/portal-notification-delivery-audit-page', description: 'Audit notifications portail avec canal, destinataire, document, statut et retry.', metrics: [{ label: 'Notifications', path: 'rows', format: 'count' }, { label: 'Statut livraison', path: 'rows.0.deliveryStatus' }, { label: 'Statut', path: 'status' }], controls: ['Canal', 'Destinataire', 'Document', 'Retry'] },
  { key: 'apiUsageAnomaly', title: 'Anomalies usage clients API', domain: 'Intégrations', route: '/enterprise-assurance/api-client-usage-anomaly-monitor-page', description: 'Monitor usage API avec client, scope, last used, pattern et action.', metrics: [{ label: 'Clients API', path: 'rows', format: 'count' }, { label: 'Action', path: 'rows.0.action' }, { label: 'Statut', path: 'status' }], controls: ['Client', 'Scope', 'Usage', 'Action'] },
  { key: 'webhookSchemaDrift', title: 'Détecteur drift schéma webhooks', domain: 'Intégrations', route: '/enterprise-assurance/webhook-schema-drift-detector-page', description: 'Drift webhooks avec event, version attendue, clés payload, risque et replay.', metrics: [{ label: 'Events', path: 'rows', format: 'count' }, { label: 'Risque', path: 'rows.0.driftRisk' }, { label: 'Statut', path: 'status' }], controls: ['Event', 'Version', 'Payload', 'Replay'] },
  { key: 'backupEvidenceFreshness', title: 'Fraîcheur preuves backup', domain: 'Opérations', route: '/enterprise-assurance/backup-evidence-freshness-monitor-page', description: 'Fraîcheur preuves backup avec type, date archive, checksum, âge et statut.', metrics: [{ label: 'Preuves', path: 'rows', format: 'count' }, { label: 'Âge', path: 'rows.0.age' }, { label: 'Statut', path: 'status' }], controls: ['Type', 'Date', 'Checksum', 'Statut'] },
  { key: 'roleSegregationMatrix', title: 'Matrice séparation des rôles', domain: 'Sécurité', route: '/enterprise-assurance/role-segregation-of-duties-matrix-page', description: 'Matrice SoD avec rôle, permission conflictuelle, module, reviewer et mitigation.', metrics: [{ label: 'Rôles', path: 'rows', format: 'count' }, { label: 'Mitigation', path: 'rows.0.mitigation' }, { label: 'Statut', path: 'status' }], controls: ['Rôle', 'Permission', 'Module', 'Mitigation'] },
  { key: 'auditEvidenceRequests', title: 'Tracker demandes preuves audit', domain: 'Audit', route: '/enterprise-assurance/audit-evidence-request-tracker-page', description: 'Tracker demandes audit avec requête, entité, due date, evidence status et reviewer.', metrics: [{ label: 'Demandes', path: 'rows', format: 'count' }, { label: 'Evidence', path: 'rows.0.evidenceStatus' }, { label: 'Statut', path: 'status' }], controls: ['Requête', 'Entité', 'Due', 'Reviewer'] },
  { key: 'releaseRollbackChecklist', title: 'Checklist rehearsal rollback release', domain: 'Release', route: '/enterprise-assurance/release-rollback-rehearsal-checklist-page', description: 'Checklist rollback avec module, backup, smoke suite, owner et readiness.', metrics: [{ label: 'Backup', path: 'backupStatus' }, { label: 'Smoke', path: 'smokeSuite', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Module', 'Backup', 'Smoke', 'Owner'] },
  { key: 'configurationDriftMonitor', title: 'Monitor drift configuration tenant', domain: 'Configuration', route: '/enterprise-assurance/tenant-configuration-drift-monitor-page', description: 'Monitor drift tenant avec setting, attendu, courant, sévérité et owner fix.', metrics: [{ label: 'Settings', path: 'rows', format: 'count' }, { label: 'Sévérité', path: 'rows.0.driftSeverity' }, { label: 'Statut', path: 'status' }], controls: ['Setting', 'Attendu', 'Courant', 'Fix'] },
  { key: 'executiveAssuranceDigest', title: 'Digest assurance direction', domain: 'Direction', route: '/enterprise-assurance/executive-assurance-digest-page', description: 'Digest assurance avec risques, couverture contrôles, preuves en retard, release et action.', metrics: [{ label: 'Risques', path: 'riskCount' }, { label: 'Couverture', path: 'controlCoverage' }, { label: 'Statut', path: 'status' }], controls: ['Risques', 'Couverture', 'Preuves', 'Release'] },
];

export const enterpriseAssuranceFeatureByKey = Object.fromEntries(
  enterpriseAssuranceFeatureDefinitions.map((definition) => [definition.key, definition]),
) as Record<EnterpriseAssuranceFeatureKey, EnterpriseAssuranceFeatureDefinition>;
