export type EnterpriseAccelerationFeatureKey =
  | 'consignmentStock'
  | 'warrantyReserve'
  | 'afterSalesRma'
  | 'subscriptionProration'
  | 'competitorBattlecard'
  | 'ecommerceReconciliation'
  | 'marketplaceSettlement'
  | 'wholesaleRebate'
  | 'retailCashAudit'
  | 'pharmaLotExpiry'
  | 'foodRecallDrill'
  | 'hotelOccupancy'
  | 'spaPackageLiability'
  | 'routeProfitability'
  | 'brokerFeeReconciliation'
  | 'fxExposure'
  | 'bouncedPaymentRecovery'
  | 'blockedPaymentRelease'
  | 'warrantyClaimReserve'
  | 'fleetClaimSettlement'
  | 'maintenanceCompliance'
  | 'projectCloseout'
  | 'consultantUtilization'
  | 'certificationRegister'
  | 'payrollLoanCompliance'
  | 'hrOnboardingPack'
  | 'executiveDigest'
  | 'supportEscalation'
  | 'partnerCapacity'
  | 'sandboxResetAudit'
  | 'invoiceMentionValidator'
  | 'bilingualPdfQueue'
  | 'vatCarryforward'
  | 'isForecast'
  | 'professionalTaxCalendar'
  | 'cnssAnomalyHeatmap'
  | 'amoReimbursements'
  | 'dataExportApproval'
  | 'apiContractDashboard'
  | 'webhookReplay'
  | 'featureAdoptionExperiment'
  | 'priceIncreaseCommunication'
  | 'customerChurnRisk'
  | 'supplierDependency'
  | 'verticalTemplateSelector';

export type EnterpriseAccelerationMetric = { label: string; path: string; format?: 'money' | 'count' | 'boolean' };

export type EnterpriseAccelerationFeatureDefinition = {
  key: EnterpriseAccelerationFeatureKey;
  title: string;
  domain: string;
  route: string;
  description: string;
  metrics: EnterpriseAccelerationMetric[];
  controls: string[];
};

export const enterpriseAccelerationFeatureDefinitions: EnterpriseAccelerationFeatureDefinition[] = [
  { key: 'consignmentStock', title: 'Stock en consignation', domain: 'Stock', route: '/enterprise-acceleration/consignment-stock-workflow-page', description: 'Consignation avec propriétaire, réception, consommation, facture fournisseur et exclusion valorisation.', metrics: [{ label: 'Propriétaire', path: 'owner' }, { label: 'Exclu valorisation', path: 'valuationExcluded', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Propriétaire', 'Réception', 'Consommation', 'Valorisation'] },
  { key: 'warrantyReserve', title: 'Réserve garantie', domain: 'Comptabilité', route: '/enterprise-acceleration/warranty-reserve-calculation-page', description: 'Calcul réserve garantie par famille, taux sinistre, coût réparation et provision.', metrics: [{ label: 'Réserve', path: 'reserve', format: 'money' }, { label: 'Taux claim', path: 'claimRate' }, { label: 'Statut', path: 'status' }], controls: ['Famille', 'Taux', 'Réparation', 'Provision'] },
  { key: 'afterSalesRma', title: 'RMA après-vente', domain: 'SAV', route: '/enterprise-acceleration/after-sales-rma-workflow-page', description: 'RMA avec preuve client, série/lot, décision réparation, avoir et mouvement stock.', metrics: [{ label: 'Statut', path: 'status' }, { label: 'Avoir', path: 'creditNoteLink' }, { label: 'Mouvement', path: 'stockMovement' }], controls: ['Preuve', 'Série/lot', 'Décision', 'Stock'] },
  { key: 'subscriptionProration', title: 'Prorata abonnement SaaS', domain: 'SaaS', route: '/enterprise-acceleration/subscription-billing-proration-page', description: 'Proration abonnement avec changement plan, split période, TVA et note facture.', metrics: [{ label: 'Total', path: 'total', format: 'money' }, { label: 'TVA', path: 'vat', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Plan', 'Période', 'TVA', 'Note'] },
  { key: 'competitorBattlecard', title: 'Battlecards concurrents Maroc', domain: 'Vente', route: '/enterprise-acceleration/moroccan-competitor-battlecard-page', description: 'Battlecards par verticale, gap fonctionnel, objection prix, preuve conformité et win/loss.', metrics: [{ label: 'Verticales', path: 'rows', format: 'count' }, { label: 'Concurrent', path: 'rows.0.competitor' }, { label: 'Statut', path: 'status' }], controls: ['Verticale', 'Gap', 'Prix', 'Conformité'] },
  { key: 'ecommerceReconciliation', title: 'Rapprochement e-commerce', domain: 'Commerce', route: '/enterprise-acceleration/ecommerce-order-reconciliation-page', description: 'Rapprochement commande marketplace avec payout, frais livraison, retour, TVA et facture.', metrics: [{ label: 'Payout', path: 'marketplacePayout', format: 'money' }, { label: 'TVA', path: 'vat', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Payout', 'Livraison', 'Retour', 'TVA'] },
  { key: 'marketplaceSettlement', title: 'Settlement vendeur marketplace', domain: 'Commerce', route: '/enterprise-acceleration/marketplace-seller-settlement-page', description: 'Settlement vendeur avec commission, retenue, batch paiement et réserve litige.', metrics: [{ label: 'Net', path: 'netSettlement', format: 'money' }, { label: 'Commission', path: 'commission', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Commission', 'Retenue', 'Batch', 'Réserve'] },
  { key: 'wholesaleRebate', title: 'Contrat remise wholesale', domain: 'Vente', route: '/enterprise-acceleration/wholesale-customer-rebate-contract-page', description: 'Contrat remise client wholesale avec tiers, accrual mensuel, avoir et preuve approbation.', metrics: [{ label: 'Accrual', path: 'monthlyAccrual', format: 'money' }, { label: 'Plan avoir', path: 'creditNotePlan' }, { label: 'Statut', path: 'status' }], controls: ['Tiers', 'Accrual', 'Avoir', 'Preuve'] },
  { key: 'retailCashAudit', title: 'Audit caisse magasin', domain: 'Retail', route: '/enterprise-acceleration/retail-store-daily-cash-audit-page', description: 'Audit caisse quotidien par agence, caissier, Z-report, dépôt et variance owner.', metrics: [{ label: 'Agence', path: 'branch' }, { label: 'Caissier', path: 'cashier' }, { label: 'Statut', path: 'status' }], controls: ['Agence', 'Caissier', 'Z-report', 'Dépôt'] },
  { key: 'pharmaLotExpiry', title: 'Lots pharma expirés', domain: 'Santé', route: '/enterprise-acceleration/pharmaceutical-lot-expiry-compliance-page', description: 'Conformité lot pharmacie avec batch, expiration, quarantaine, rappel et destruction.', metrics: [{ label: 'Batch', path: 'batch' }, { label: 'Quarantaine', path: 'quarantine', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Lot', 'Expiration', 'Quarantaine', 'Destruction'] },
  { key: 'foodRecallDrill', title: 'Drill rappel alimentaire', domain: 'Agro', route: '/enterprise-acceleration/food-traceability-recall-drill-page', description: 'Drill rappel agro avec lot fournisseur, livraisons clients, notifications et hold stock.', metrics: [{ label: 'Livraisons', path: 'customerDeliveries', format: 'count' }, { label: 'Hold stock', path: 'stockHold', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Lot', 'Livraisons', 'Notifications', 'Hold'] },
  { key: 'hotelOccupancy', title: 'Revenu occupation hôtel', domain: 'Hôtellerie', route: '/enterprise-acceleration/hotel-occupancy-revenue-dashboard-page', description: 'Dashboard hôtel avec chambres, nuitées, taxe ville placeholder, TVA et mix paiement.', metrics: [{ label: 'Nuitées', path: 'nights' }, { label: 'Revenu', path: 'revenue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Chambres', 'Nuitées', 'Taxe', 'Paiements'] },
  { key: 'spaPackageLiability', title: 'Passif packages spa', domain: 'Services', route: '/enterprise-acceleration/salon-spa-package-liability-ledger-page', description: 'Ledger packages salon/spa avec sessions prépayées, consommation, expiration et revenu.', metrics: [{ label: 'Sessions', path: 'prepaidSessions' }, { label: 'Passif', path: 'liability', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Prépayé', 'Consommé', 'Expiration', 'Revenu'] },
  { key: 'routeProfitability', title: 'Profitabilité route logistique', domain: 'Logistique', route: '/enterprise-acceleration/logistics-route-profitability-dashboard-page', description: 'Profitabilité route avec véhicule, chauffeur, fuel, péages, revenu livraison et marge.', metrics: [{ label: 'Véhicule', path: 'vehicle' }, { label: 'Marge', path: 'margin', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Véhicule', 'Fuel', 'Péages', 'Marge'] },
  { key: 'brokerFeeReconciliation', title: 'Rapprochement transitaire', domain: 'Import', route: '/enterprise-acceleration/customs-broker-fee-reconciliation-page', description: 'Rapprochement transitaire avec DUM, facture, débours, TVA et landed cost.', metrics: [{ label: 'DUM', path: 'dumReference' }, { label: 'Allocation', path: 'landedCostAllocation', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['DUM', 'Facture', 'Débours', 'Landed cost'] },
  { key: 'fxExposure', title: 'Exposition fournisseur devise', domain: 'Trésorerie', route: '/enterprise-acceleration/international-supplier-fx-exposure-page', description: 'Exposition FX fournisseur avec devise, échéance, scénario taux et gain/perte.', metrics: [{ label: 'Devise', path: 'currency' }, { label: 'Gain/perte', path: 'gainLossPreview', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Devise', 'Échéance', 'Scénario', 'Gain/perte'] },
  { key: 'bouncedPaymentRecovery', title: 'Recouvrement paiement rejeté', domain: 'Recouvrement', route: '/enterprise-acceleration/customer-bounced-payment-recovery-page', description: 'Recouvrement paiement rejeté avec frais, dunning, promesse, note légale et hold.', metrics: [{ label: 'Frais', path: 'fees', format: 'money' }, { label: 'Hold', path: 'accountHold', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Frais', 'Dunning', 'Promesse', 'Hold'] },
  { key: 'blockedPaymentRelease', title: 'Déblocage paiement fournisseur', domain: 'Achats', route: '/enterprise-acceleration/supplier-blocked-payment-release-page', description: 'Déblocage paiement fournisseur avec résolution litige, validation docs, approbation et fichier banque.', metrics: [{ label: 'Validation', path: 'documentValidation' }, { label: 'Approbation', path: 'approval' }, { label: 'Statut', path: 'status' }], controls: ['Litige', 'Documents', 'Approbation', 'Banque'] },
  { key: 'warrantyClaimReserve', title: 'Réserve claim garantie client', domain: 'SAV', route: '/enterprise-acceleration/customer-warranty-claim-reserve-page', description: 'Réserve claim garantie client par famille, âge, coût, probabilité et écriture.', metrics: [{ label: 'Réserve', path: 'reserve', format: 'money' }, { label: 'Probabilité', path: 'replacementProbability' }, { label: 'Statut', path: 'status' }], controls: ['Famille', 'Âge', 'Coût', 'Écriture'] },
  { key: 'fleetClaimSettlement', title: 'Sinistre assurance flotte', domain: 'Flotte', route: '/enterprise-acceleration/fleet-insurance-claim-settlement-page', description: 'Sinistre flotte avec accident, facture réparation, paiement assureur, franchise et journal.', metrics: [{ label: 'Paiement', path: 'insurerPayment', format: 'money' }, { label: 'Franchise', path: 'deductible', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Accident', 'Réparation', 'Assureur', 'Journal'] },
  { key: 'maintenanceCompliance', title: 'Score maintenance préventive', domain: 'Maintenance', route: '/enterprise-acceleration/maintenance-preventive-compliance-score-page', description: 'Score maintenance avec jobs planifiés, actifs overdue, pièces, risque downtime et owner.', metrics: [{ label: 'Score', path: 'score' }, { label: 'Overdue', path: 'overdueAssets' }, { label: 'Statut', path: 'status' }], controls: ['Jobs', 'Overdue', 'Pièces', 'Owner'] },
  { key: 'projectCloseout', title: 'Closeout profitabilité projet', domain: 'Projets', route: '/enterprise-acceleration/project-profitability-closeout-checklist-page', description: 'Closeout projet avec revenu, WIP reversal, retention, lessons learned et archive.', metrics: [{ label: 'Marge', path: 'margin', format: 'money' }, { label: 'Retention', path: 'retention', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Revenu', 'WIP', 'Retention', 'Archive'] },
  { key: 'consultantUtilization', title: 'Utilisation consultants', domain: 'Services', route: '/enterprise-acceleration/consultant-utilization-dashboard-page', description: 'Utilisation consultant avec heures billables, bench, retainer, voyage et marge.', metrics: [{ label: 'Billable', path: 'billableHours' }, { label: 'Marge', path: 'grossMargin', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Billable', 'Bench', 'Retainer', 'Marge'] },
  { key: 'certificationRegister', title: 'Registre certifications salariés', domain: 'RH', route: '/enterprise-acceleration/employee-certification-register-page', description: 'Registre certifications avec échéance, coût formation, exigence rôle et renouvellement.', metrics: [{ label: 'Certifications', path: 'rows', format: 'count' }, { label: 'Coût', path: 'rows.0.trainingCost', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Certificat', 'Échéance', 'Coût', 'Renouvellement'] },
  { key: 'payrollLoanCompliance', title: 'Conformité prêts paie', domain: 'Paie', route: '/enterprise-acceleration/payroll-loan-compliance-dashboard-page', description: 'Dashboard prêt salarié avec solde, cap retenue, consentement et mention bulletin.', metrics: [{ label: 'Prêts', path: 'rows', format: 'count' }, { label: 'Solde', path: 'rows.0.outstandingBalance', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Solde', 'Cap', 'Consentement', 'Bulletin'] },
  { key: 'hrOnboardingPack', title: 'Pack documents onboarding RH', domain: 'RH', route: '/enterprise-acceleration/hr-onboarding-document-pack-page', description: 'Pack onboarding RH avec contrat, CNSS, CIN, RIB, visite médicale et archive restreinte.', metrics: [{ label: 'Documents', path: 'documents', format: 'count' }, { label: 'Archive', path: 'restrictedArchive' }, { label: 'Statut', path: 'status' }], controls: ['Contrat', 'CNSS', 'CIN', 'Archive'] },
  { key: 'executiveDigest', title: 'Digest KPI abonnement', domain: 'Direction', route: '/enterprise-acceleration/executive-kpi-subscription-digest-page', description: 'Digest direction avec usage, revenu, churn risk, blockers conformité et support.', metrics: [{ label: 'Churn', path: 'churnRisk' }, { label: 'Revenu', path: 'revenue', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Usage', 'Revenu', 'Churn', 'Support'] },
  { key: 'supportEscalation', title: 'Matrice escalation support', domain: 'Support', route: '/enterprise-acceleration/support-sla-escalation-matrix-page', description: 'Matrice SLA support avec sévérité, deadline, équipe, notice client et breach.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Sévérité', path: 'rows.0.severity' }, { label: 'Statut', path: 'status' }], controls: ['Sévérité', 'Deadline', 'Équipe', 'Notice'] },
  { key: 'partnerCapacity', title: 'Capacité partenaire implémentation', domain: 'Partenaires', route: '/enterprise-acceleration/implementation-partner-capacity-planning-page', description: 'Capacité partenaire avec consultants, workload clients, deadlines, risque et marge.', metrics: [{ label: 'Clients', path: 'clientWorkload' }, { label: 'Risque', path: 'riskScore' }, { label: 'Statut', path: 'status' }], controls: ['Consultants', 'Clients', 'Risques', 'Marge'] },
  { key: 'sandboxResetAudit', title: 'Audit reset sandbox tenant', domain: 'Admin', route: '/enterprise-acceleration/tenant-sandbox-reset-audit-page', description: 'Audit reset sandbox avec modules, archives préservées, acteur, timestamp et restore point.', metrics: [{ label: 'Modules', path: 'modulesReset', format: 'count' }, { label: 'Archives', path: 'preservedLegalArchives' }, { label: 'Statut', path: 'status' }], controls: ['Modules', 'Archives', 'Acteur', 'Restore'] },
  { key: 'invoiceMentionValidator', title: 'Validateur mentions facture', domain: 'Conformité', route: '/enterprise-acceleration/moroccan-invoice-legal-mention-validator-page', description: 'Validation mentions facture Maroc ICE, IF, RC, CNSS, arabe et numérotation.', metrics: [{ label: 'Checks', path: 'checks', format: 'count' }, { label: 'Statut', path: 'status' }, { label: 'Numéro', path: 'checks.5.ok', format: 'boolean' }], controls: ['ICE', 'IF', 'RC', 'Numérotation'] },
  { key: 'bilingualPdfQueue', title: 'Queue qualité PDF bilingue', domain: 'Documents', route: '/enterprise-acceleration/bilingual-pdf-quality-queue-page', description: 'Queue qualité PDF bilingue avec type document, RTL, labels arabes, reviewer et statut.', metrics: [{ label: 'Documents', path: 'rows', format: 'count' }, { label: 'Reviewer', path: 'rows.0.reviewer' }, { label: 'Archives', path: 'archiveCount' }], controls: ['Type', 'RTL', 'Labels', 'Reviewer'] },
  { key: 'vatCarryforward', title: 'Report crédit TVA', domain: 'Fiscalité', route: '/enterprise-acceleration/vat-credit-carryforward-tracker-page', description: 'Tracker report crédit TVA avec période, déclaration, offset, remboursement et preuve.', metrics: [{ label: 'Période', path: 'period' }, { label: 'Offset', path: 'offset', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Période', 'Déclaration', 'Offset', 'Preuve'] },
  { key: 'isForecast', title: 'Prévision acomptes IS', domain: 'Fiscalité', route: '/enterprise-acceleration/is-installment-forecast-page', description: 'Prévision IS avec profit imposable, base N-1, échéances et impact cash.', metrics: [{ label: 'Impact cash', path: 'cashImpact', format: 'money' }, { label: 'Échéances', path: 'dueDates', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Profit', 'Base', 'Échéances', 'Cash'] },
  { key: 'professionalTaxCalendar', title: 'Calendrier taxe professionnelle', domain: 'Fiscalité', route: '/enterprise-acceleration/professional-tax-due-calendar-page', description: 'Calendrier taxe professionnelle avec commune, valeur locative, taux placeholder, échéance et archive.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Commune', path: 'rows.0.municipality' }, { label: 'Statut', path: 'status' }], controls: ['Commune', 'Valeur', 'Taux', 'Archive'] },
  { key: 'cnssAnomalyHeatmap', title: 'Heatmap anomalies CNSS', domain: 'Paie', route: '/enterprise-acceleration/cnss-payroll-anomaly-heatmap-page', description: 'Heatmap CNSS par agence, contrat, identifiants manquants, doublons et owner correction.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Owner', path: 'rows.0.correctionOwner' }, { label: 'Statut', path: 'status' }], controls: ['Agence', 'Contrat', 'CNSS', 'Owner'] },
  { key: 'amoReimbursements', title: 'Suivi remboursements AMO', domain: 'Paie', route: '/enterprise-acceleration/amo-reimbursement-tracking-page', description: 'Placeholder suivi AMO avec salarié, date claim, montant, statut et coffre document.', metrics: [{ label: 'Claims', path: 'rows', format: 'count' }, { label: 'Montant', path: 'rows.0.amount', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Salarié', 'Date', 'Montant', 'Coffre'] },
  { key: 'dataExportApproval', title: 'Workflow approbation export data', domain: 'Sécurité', route: '/enterprise-acceleration/data-export-approval-workflow-page', description: 'Approbation export avec demandeur, dataset, base légale, approver, checksum et expiry.', metrics: [{ label: 'Dataset', path: 'dataset' }, { label: 'Expiry', path: 'expiry' }, { label: 'Statut', path: 'status' }], controls: ['Demandeur', 'Dataset', 'Base légale', 'Checksum'] },
  { key: 'apiContractDashboard', title: 'Contrats intégration API', domain: 'Intégrations', route: '/enterprise-acceleration/api-integration-contract-dashboard-page', description: 'Dashboard contrats API avec partenaire, scopes, rate limits, webhook et rotation clé.', metrics: [{ label: 'Contrats', path: 'rows', format: 'count' }, { label: 'Partenaire', path: 'rows.0.partner' }, { label: 'Statut', path: 'status' }], controls: ['Partenaire', 'Scopes', 'Rate limits', 'Rotation'] },
  { key: 'webhookReplay', title: 'Replay incident webhook', domain: 'Intégrations', route: '/enterprise-acceleration/webhook-incident-replay-workflow-page', description: 'Replay webhook avec événement, signature, retries, réponse cible et audit.', metrics: [{ label: 'Event', path: 'event' }, { label: 'Retries', path: 'retryCount' }, { label: 'Statut', path: 'status' }], controls: ['Événement', 'Signature', 'Retries', 'Audit'] },
  { key: 'featureAdoptionExperiment', title: 'Expérimentation adoption feature', domain: 'SaaS', route: '/enterprise-acceleration/tenant-feature-adoption-experiment-dashboard-page', description: 'Dashboard expérimentation feature avec cohorte, flag, activation, rétention et rollback.', metrics: [{ label: 'Cohorte', path: 'cohort' }, { label: 'Activation', path: 'activationMetric' }, { label: 'Statut', path: 'status' }], controls: ['Cohorte', 'Feature flag', 'Activation', 'Rollback'] },
  { key: 'priceIncreaseCommunication', title: 'Communication hausse tarifaire', domain: 'SaaS', route: '/enterprise-acceleration/price-increase-communication-workflow-page', description: 'Workflow hausse tarifaire avec segment, date effet, templates FR/AR, approbation et impact client.', metrics: [{ label: 'Segment', path: 'segment' }, { label: 'Impact clients', path: 'customerImpact' }, { label: 'Statut', path: 'status' }], controls: ['Segment', 'Préavis', 'Templates FR/AR', 'Approbation'] },
  { key: 'customerChurnRisk', title: 'Prédicteur churn client', domain: 'Succès client', route: '/enterprise-acceleration/customer-churn-risk-predictor-page', description: 'Prédicteur churn avec solde en retard, tickets support, adoption, renouvellement et plan action.', metrics: [{ label: 'Solde retard', path: 'overdueBalance', format: 'money' }, { label: 'Score risque', path: 'riskScore' }, { label: 'Statut', path: 'status' }], controls: ['Solde', 'Support', 'Adoption', 'Plan action'] },
  { key: 'supplierDependency', title: 'Concentration dépendance fournisseur', domain: 'Achats', route: '/enterprise-acceleration/supplier-dependency-concentration-report-page', description: 'Rapport dépendance fournisseur avec part dépense, alternative, note risque et owner mitigation.', metrics: [{ label: 'Fournisseurs', path: 'rows', format: 'count' }, { label: 'Part spend', path: 'rows.0.spendShare' }, { label: 'Statut', path: 'status' }], controls: ['Spend', 'Alternative', 'Risque', 'Owner'] },
  { key: 'verticalTemplateSelector', title: 'Sélecteur template verticale Maroc', domain: 'Onboarding', route: '/enterprise-acceleration/moroccan-vertical-template-selector-page', description: 'Sélecteur verticale Maroc avec industrie, mapping PCGE, workflows, documents et données démo.', metrics: [{ label: 'Industrie', path: 'industry' }, { label: 'Workflows', path: 'workflows', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Industrie', 'PCGE', 'Workflows', 'Documents'] },
];

export const enterpriseAccelerationFeatureByKey = Object.fromEntries(
  enterpriseAccelerationFeatureDefinitions.map((definition) => [definition.key, definition]),
) as Record<EnterpriseAccelerationFeatureKey, EnterpriseAccelerationFeatureDefinition>;
