export type EnterpriseOperationsFeatureKey =
  | 'transporterReconciliation'
  | 'securityIncident'
  | 'obsolescenceProvision'
  | 'importVatRecovery'
  | 'threeWayMatch'
  | 'supplierPaymentRun'
  | 'dunningTemplates'
  | 'collectionCallLog'
  | 'cashReceiptAudit'
  | 'posZReport'
  | 'bankReconciliationPdf'
  | 'bankTransferAdapter'
  | 'payrollBankTransfer'
  | 'benefitInKind'
  | 'endOfContract'
  | 'occupationalHealth'
  | 'disciplinaryWorkflow'
  | 'headcountDashboard'
  | 'componentShortage'
  | 'subcontracting'
  | 'downtimeAnalytics'
  | 'mileageReimbursement'
  | 'fuelCardImport'
  | 'projectCommitments'
  | 'timesheetApproval'
  | 'portalPaymentPromise'
  | 'supplierCertificateRenewal'
  | 'accountantAnnotations'
  | 'legalArchiveBundle'
  | 'dgiVatPayload'
  | 'irSalaryPayload'
  | 'cnssAmendment'
  | 'publicProcurement'
  | 'retentionGuarantee'
  | 'branchPnl'
  | 'multiCompanyDashboard'
  | 'securityChecklist'
  | 'permissionSimulator'
  | 'auditAnomalies'
  | 'customerProfitability';

export type EnterpriseOperationsMetric = {
  label: string;
  path: string;
  format?: 'money' | 'count' | 'boolean';
};

export type EnterpriseOperationsFeatureDefinition = {
  key: EnterpriseOperationsFeatureKey;
  title: string;
  domain: string;
  route: string;
  description: string;
  metrics: EnterpriseOperationsMetric[];
  controls: string[];
};

export const enterpriseOperationsFeatureDefinitions: EnterpriseOperationsFeatureDefinition[] = [
  { key: 'transporterReconciliation', title: 'Rapprochement transporteur', domain: 'Logistique', route: '/enterprise-operations/transporter-invoice-reconciliation-page', description: 'Rapprochement facture transporteur avec tarif route, preuve de livraison, pénalités et surcharge carburant.', metrics: [{ label: 'Statut', path: 'reconciliationStatus' }, { label: 'Montant', path: 'invoiceAmount', format: 'money' }, { label: 'Preuve', path: 'deliveryProofStatus' }], controls: ['Tarif route', 'Preuve livraison', 'Pénalités', 'Surcharge carburant'] },
  { key: 'securityIncident', title: 'Incident sécurité dépôt', domain: 'Stock', route: '/enterprise-operations/warehouse-security-incident-log-page', description: 'Journal d’incident dépôt avec produit, quantité, référence CCTV, assurance et proposition de sortie stock.', metrics: [{ label: 'Statut', path: 'status' }, { label: 'Quantité', path: 'quantity' }, { label: 'Valorisation', path: 'stockAdjustmentProposal.valuation', format: 'money' }], controls: ['Produit', 'CCTV', 'Assurance', 'Ajustement stock'] },
  { key: 'obsolescenceProvision', title: 'Provision obsolescence', domain: 'Stock', route: '/enterprise-operations/inventory-obsolescence-provision-page', description: 'Proposition de provision par âge stock, famille, valeur CUMP et validation comptable.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Provision', path: 'totalProvision', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Âge stock', 'Famille', 'CUMP', 'Approbation comptable'] },
  { key: 'importVatRecovery', title: 'TVA import récupérable', domain: 'Fiscalité', route: '/enterprise-operations/moroccan-import-vat-recovery-page', description: 'Suivi TVA douane récupérable par DUM, reçu, facture fournisseur et période déductible.', metrics: [{ label: 'DUM', path: 'rows', format: 'count' }, { label: 'Statut', path: 'status' }, { label: 'TVA', path: 'rows.0.customsVat', format: 'money' }], controls: ['DUM', 'Reçu douane', 'Facture fournisseur', 'Période déductible'] },
  { key: 'threeWayMatch', title: 'Three-way match achat', domain: 'Achats', route: '/enterprise-operations/purchase-three-way-match-page', description: 'Contrôle commande, réception, facture fournisseur, landed cost et exceptions d’approbation.', metrics: [{ label: 'Statut', path: 'status' }, { label: 'Écart', path: 'variance', format: 'money' }, { label: 'Exceptions', path: 'approvalExceptions', format: 'count' }], controls: ['BC', 'Réception', 'Facture', 'Landed cost'] },
  { key: 'supplierPaymentRun', title: 'Run paiements fournisseurs', domain: 'Trésorerie', route: '/enterprise-operations/supplier-payment-run-approval-page', description: 'Approbation paiements fournisseurs avec solde banque, factures dues, litiges bloquants et prévision trésorerie.', metrics: [{ label: 'Statut', path: 'approvalStatus' }, { label: 'Factures dues', path: 'dueInvoices' }, { label: 'Prévision', path: 'treasuryForecast', format: 'money' }], controls: ['Solde banque', 'Factures dues', 'Litiges', 'Prévision'] },
  { key: 'dunningTemplates', title: 'Templates relance client', domain: 'Recouvrement', route: '/enterprise-operations/customer-dunning-email-templates-page', description: 'Variantes de relance FR/AR selon niveau, préférence langue et identifiants légaux.', metrics: [{ label: 'Variantes', path: 'variants', format: 'count' }, { label: 'ICE', path: 'legalIdentifiers.ice' }, { label: 'RC', path: 'legalIdentifiers.rc' }], controls: ['Français', 'Arabe', 'Niveau relance', 'ICE/RC'] },
  { key: 'collectionCallLog', title: 'Journal appels recouvrement', domain: 'Recouvrement', route: '/enterprise-operations/collection-call-log-page', description: 'Journal d’appel avec promesse, escalade litige, prochain responsable et pièces jointes.', metrics: [{ label: 'Appels', path: 'rows', format: 'count' }, { label: 'Statut', path: 'status' }, { label: 'Owner', path: 'rows.0.nextOwner' }], controls: ['Promesse', 'Litige', 'Owner', 'Pièces'] },
  { key: 'cashReceiptAudit', title: 'Audit reçus caisse', domain: 'POS', route: '/enterprise-operations/cash-receipt-numbering-audit-page', description: 'Audit numérotation reçus caisse: trous, doublons, série agence et responsabilité caissier.', metrics: [{ label: 'Reçus', path: 'receipts', format: 'count' }, { label: 'Trous', path: 'gaps', format: 'count' }, { label: 'Caissier', path: 'cashierId' }], controls: ['Trous', 'Doublons', 'Série agence', 'Caissier'] },
  { key: 'posZReport', title: 'Clôture Z-report POS', domain: 'POS', route: '/enterprise-operations/pos-z-report-closure-page', description: 'Clôture Z-report avec TVA, split cash/carte, remboursements et signature superviseur.', metrics: [{ label: 'Statut', path: 'closureStatus' }, { label: 'TVA', path: 'taxTotals', format: 'money' }, { label: 'Remboursements', path: 'refunds' }], controls: ['TVA', 'Cash/carte', 'Remboursements', 'Signature'] },
  { key: 'bankReconciliationPdf', title: 'PDF rapprochement bancaire', domain: 'Banque', route: '/enterprise-operations/bank-reconciliation-statement-pdf-page', description: 'État PDF de rapprochement avec lignes rapprochées/non rapprochées, soldes et visa réviseur.', metrics: [{ label: 'Rapprochées', path: 'matchedLines' }, { label: 'Non rapprochées', path: 'unmatchedLines' }, { label: 'Visa', path: 'reviewerSignOff' }], controls: ['Lignes', 'Soldes', 'Visa', 'Archive'] },
  { key: 'bankTransferAdapter', title: 'Adapter fichier virement', domain: 'Banque', route: '/enterprise-operations/bank-transfer-payment-file-adapter-page', description: 'Interface adapter fichier virement avec format banque, chaîne d’approbation et polling statut.', metrics: [{ label: 'État', path: 'submissionState' }, { label: 'Étapes', path: 'statusPolling', format: 'count' }, { label: 'Format', path: 'bankFormat' }], controls: ['Format banque', 'Approbation', 'Polling', 'Archive'] },
  { key: 'payrollBankTransfer', title: 'Export virement paie', domain: 'Paie', route: '/enterprise-operations/payroll-bank-transfer-export-page', description: 'Export virement paie avec validation RIB salarié, total net et preuve approbation.', metrics: [{ label: 'Salariés', path: 'rows', format: 'count' }, { label: 'Net', path: 'netSalaryTotal', format: 'money' }, { label: 'RIB', path: 'employeeRibValidation', format: 'boolean' }], controls: ['RIB', 'Net salaire', 'Preuve', 'Export'] },
  { key: 'benefitInKind', title: 'Avantages en nature', domain: 'Paie', route: '/enterprise-operations/payroll-benefit-in-kind-tracking-page', description: 'Suivi voiture, logement, téléphone et aperçu base imposable.', metrics: [{ label: 'Avantages', path: 'benefits', format: 'count' }, { label: 'Base', path: 'taxableBasePreview', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Voiture', 'Logement', 'Téléphone', 'IR'] },
  { key: 'endOfContract', title: 'Solde tout compte', domain: 'RH', route: '/enterprise-operations/payroll-end-of-contract-settlement-page', description: 'Règlement fin de contrat avec congés, indemnité placeholder, bulletin final et archive.', metrics: [{ label: 'Congés', path: 'leaveBalance' }, { label: 'Indemnité', path: 'indemnityPlaceholder', format: 'money' }, { label: 'Bulletin', path: 'finalPayslipStatus' }], controls: ['Congés', 'Indemnité', 'Bulletin final', 'Archive'] },
  { key: 'occupationalHealth', title: 'Santé au travail', domain: 'RH', route: '/enterprise-operations/occupational-health-reminders-page', description: 'Rappels documents santé avec accès restreint, date renouvellement et coffre RH.', metrics: [{ label: 'Rappels', path: 'rows', format: 'count' }, { label: 'Date', path: 'rows.0.renewalDate' }, { label: 'Statut', path: 'rows.0.status' }], controls: ['Accès restreint', 'Renouvellement', 'Coffre RH', 'Preuve'] },
  { key: 'disciplinaryWorkflow', title: 'Workflow disciplinaire', domain: 'RH', route: '/enterprise-operations/employee-disciplinary-workflow-page', description: 'Workflow disciplinaire avec notes restreintes, décision, appel et preuve légale.', metrics: [{ label: 'Décision', path: 'decision' }, { label: 'Appel', path: 'appealStatus' }, { label: 'Notes', path: 'restrictedNotes', format: 'boolean' }], controls: ['Notes', 'Décision', 'Appel', 'Preuve'] },
  { key: 'headcountDashboard', title: 'Effectif RH', domain: 'RH', route: '/enterprise-operations/hr-headcount-dashboard-page', description: 'Dashboard effectif par contrat, ville, département, tranche salariale et readiness CNSS.', metrics: [{ label: 'Salariés', path: 'rows', format: 'count' }, { label: 'CNSS', path: 'cnssReadiness' }, { label: 'Ville', path: 'rows.0.city' }], controls: ['Contrat', 'Ville', 'Département', 'CNSS'] },
  { key: 'componentShortage', title: 'Ruptures composants', domain: 'Production', route: '/enterprise-operations/production-component-shortage-forecast-page', description: 'Prévision rupture par BOM, commandes ouvertes, réservations et délai achat.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Rupture', path: 'rows.0.shortage' }, { label: 'Statut', path: 'status' }], controls: ['BOM', 'Commandes', 'Réservations', 'Délai achat'] },
  { key: 'subcontracting', title: 'Sous-traitance production', domain: 'Production', route: '/enterprise-operations/production-subcontracting-workflow-page', description: 'Sous-traitance production avec fournisseur, composants sortis, réception, qualité et coût.', metrics: [{ label: 'Réception', path: 'receiptStatus' }, { label: 'Qualité', path: 'qualityCheckStatus' }, { label: 'Coût', path: 'costRollup', format: 'money' }], controls: ['Fournisseur', 'Composants', 'Réception', 'Qualité'] },
  { key: 'downtimeAnalytics', title: 'Analyse downtime', domain: 'Maintenance', route: '/enterprise-operations/maintenance-downtime-analytics-page', description: 'Analyse arrêt maintenance par actif, cause, pièces, technicien et production perdue.', metrics: [{ label: 'Arrêts', path: 'rows', format: 'count' }, { label: 'Perte', path: 'rows.0.lostProductionEstimate', format: 'money' }, { label: 'Technicien', path: 'rows.0.technician' }], controls: ['Actif', 'Cause', 'Pièces', 'Perte production'] },
  { key: 'mileageReimbursement', title: 'Remboursement kilométrique', domain: 'Flotte', route: '/enterprise-operations/fleet-mileage-reimbursement-page', description: 'Workflow kilomètres flotte avec route, chauffeur, taux, approbation et lien paie/compta.', metrics: [{ label: 'Montant', path: 'amount', format: 'money' }, { label: 'Statut', path: 'approvalStatus' }, { label: 'Route', path: 'route' }], controls: ['Route', 'Chauffeur', 'Taux', 'Lien paie/compta'] },
  { key: 'fuelCardImport', title: 'Import cartes carburant', domain: 'Flotte', route: '/enterprise-operations/fleet-fuel-card-import-sandbox-page', description: 'Sandbox import carte carburant avec numéro carte, véhicule, doublon et exception.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Exceptions', path: 'exceptionPreview', format: 'count' }, { label: 'Statut', path: 'status' }], controls: ['Carte', 'Véhicule', 'Doublon', 'Exception'] },
  { key: 'projectCommitments', title: 'Engagements projet', domain: 'Projets', route: '/enterprise-operations/project-procurement-commitment-report-page', description: 'Rapport engagements projet par budget, BC, réception, facture fournisseur et forecast restant.', metrics: [{ label: 'Budget', path: 'budget', format: 'money' }, { label: 'Restant', path: 'remainingForecast', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Budget', 'BC', 'Réceptions', 'Forecast'] },
  { key: 'timesheetApproval', title: 'Approbation timesheets', domain: 'Projets', route: '/enterprise-operations/project-timesheet-approval-workflow-page', description: 'Workflow timesheet avec salarié, taux, facturable, approbation client et impact WIP.', metrics: [{ label: 'Entrées', path: 'entries', format: 'count' }, { label: 'Statut', path: 'approvalStatus' }, { label: 'WIP', path: 'wipImpact', format: 'money' }], controls: ['Salarié', 'Taux', 'Facturable', 'WIP'] },
  { key: 'portalPaymentPromise', title: 'Promesse portail client', domain: 'Portails', route: '/enterprise-operations/customer-portal-payment-promise-page', description: 'Promesse de paiement portail avec token sécurisé, messages, échéance et audit.', metrics: [{ label: 'Messages', path: 'messageThread', format: 'count' }, { label: 'Échéance', path: 'dueDate' }, { label: 'Audit', path: 'auditTrail' }], controls: ['Token', 'Messages', 'Échéance', 'Audit'] },
  { key: 'supplierCertificateRenewal', title: 'Renouvellement certificats', domain: 'Portails', route: '/enterprise-operations/supplier-portal-certificate-renewal-page', description: 'Workflow renouvellement attestation fournisseur avec upload placeholder, validation et blockers.', metrics: [{ label: 'Statut', path: 'validationStatus' }, { label: 'Blockers', path: 'blockerAlerts', format: 'count' }, { label: 'Date', path: 'renewalDueDate' }], controls: ['Upload', 'Validation', 'Blockers', 'Rappel'] },
  { key: 'accountantAnnotations', title: 'Annotations comptables', domain: 'Comptabilité', route: '/enterprise-operations/accountant-review-annotations-page', description: 'Annotations sur factures, journaux, paies et déclarations avec résolution.', metrics: [{ label: 'Commentaires', path: 'comments', format: 'count' }, { label: 'Résolutions', path: 'resolutionStatus', format: 'count' }, { label: 'Premier', path: 'resolutionStatus.0.status' }], controls: ['Factures', 'Journaux', 'Paie', 'Résolution'] },
  { key: 'legalArchiveBundle', title: 'Bundle archive légale', domain: 'Conformité', route: '/enterprise-operations/legal-archive-export-bundle-page', description: 'Export archive légale par exercice avec manifest, checksums et vérification restore.', metrics: [{ label: 'Manifest', path: 'manifest', format: 'count' }, { label: 'Restore', path: 'restoreVerification', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['Manifest', 'Checksums', 'Restore', 'Exercice'] },
  { key: 'dgiVatPayload', title: 'Payload TVA DGI sandbox', domain: 'Fiscalité', route: '/enterprise-operations/dgi-vat-declaration-payload-page', description: 'Builder payload TVA DGI sandbox avec lignes, prorata, validations et archive.', metrics: [{ label: 'Messages', path: 'validationMessages', format: 'count' }, { label: 'État', path: 'submissionState' }, { label: 'Archive', path: 'archiveEvidenceId' }], controls: ['Lignes', 'Prorata', 'Validation', 'Archive'] },
  { key: 'irSalaryPayload', title: 'Payload IR salaires', domain: 'Fiscalité', route: '/enterprise-operations/ir-salary-declaration-payload-page', description: 'Builder payload IR salaires avec bulletins, identifiants salariés et validations.', metrics: [{ label: 'Salariés', path: 'employeeIdentifiers', format: 'count' }, { label: 'Messages', path: 'validationMessages', format: 'count' }, { label: 'État', path: 'submissionState' }], controls: ['Bulletins', 'CIN', 'CNSS', 'Validation'] },
  { key: 'cnssAmendment', title: 'Amendement CNSS', domain: 'Paie', route: '/enterprise-operations/cnss-declaration-amendment-workflow-page', description: 'Workflow amendement CNSS avec lignes corrigées, motif, approbation et archive Damancom.', metrics: [{ label: 'Statut', path: 'status' }, { label: 'Lignes', path: 'correctedLines' }, { label: 'Archive', path: 'damancomArchive' }], controls: ['Lignes', 'Motif', 'Approbation', 'Damancom'] },
  { key: 'publicProcurement', title: 'Client marché public', domain: 'CRM', route: '/enterprise-operations/moroccan-public-procurement-customer-page', description: 'Flag marché public avec retenue, conditions paiement, documents et exposition.', metrics: [{ label: 'Exposition', path: 'exposure', format: 'money' }, { label: 'Paiement', path: 'paymentTermsDays' }, { label: 'Statut', path: 'status' }], controls: ['Retenue', 'Paiement', 'Documents', 'Exposition'] },
  { key: 'retentionGuarantee', title: 'Retenue de garantie BTP', domain: 'Projets', route: '/enterprise-operations/construction-retention-guarantee-tracking-page', description: 'Suivi retenue de garantie construction avec holdback, jalon libération et proposition comptable.', metrics: [{ label: 'Holdback', path: 'holdback', format: 'money' }, { label: 'Jalon', path: 'releaseMilestone' }, { label: 'Statut', path: 'status' }], controls: ['Holdback', 'Jalon', 'Garantie', 'Compta'] },
  { key: 'branchPnl', title: 'P&L centre de profit', domain: 'Branches', route: '/enterprise-operations/branch-profit-center-pnl-page', description: 'P&L agence par ventes, COGS, paie, loyer et frais partagés.', metrics: [{ label: 'Ventes', path: 'sales', format: 'money' }, { label: 'Paie', path: 'payrollAllocation', format: 'money' }, { label: 'P&L', path: 'pnl', format: 'money' }], controls: ['Ventes', 'COGS', 'Paie', 'Overhead'] },
  { key: 'multiCompanyDashboard', title: 'Dashboard multi-sociétés', domain: 'Cabinet', route: '/enterprise-operations/multi-company-accountant-dashboard-page', description: 'Dashboard cabinet avec conformité, blockers, échéances et workload scoring.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Blockers', path: 'rows.0.blockers' }, { label: 'Statut', path: 'status' }], controls: ['Conformité', 'Blockers', 'Déclarations', 'Workload'] },
  { key: 'securityChecklist', title: 'Checklist sécurité tenant', domain: 'Sécurité', route: '/enterprise-operations/tenant-security-review-checklist-page', description: 'Checklist sécurité avec MFA, API keys, utilisateurs inactifs, exports et actions admin.', metrics: [{ label: 'Checks', path: 'checks', format: 'count' }, { label: 'MFA', path: 'checks.0.done', format: 'boolean' }, { label: 'Statut', path: 'status' }], controls: ['MFA', 'API keys', 'Utilisateurs', 'Exports'] },
  { key: 'permissionSimulator', title: 'Simulateur permissions', domain: 'Sécurité', route: '/enterprise-operations/role-permission-simulator-page', description: 'Simulation permission par module, action, agence, montant et explication allow/deny.', metrics: [{ label: 'Décision', path: 'expected' }, { label: 'Montant', path: 'amount', format: 'money' }, { label: 'Module', path: 'module' }], controls: ['Module', 'Action', 'Agence', 'Montant'] },
  { key: 'auditAnomalies', title: 'Détecteur anomalies audit', domain: 'Sécurité', route: '/enterprise-operations/audit-anomaly-detector-page', description: 'Détection changements hors horaires, remises fortes, journaux manuels et paie.', metrics: [{ label: 'Lignes', path: 'rows', format: 'count' }, { label: 'Journaux', path: 'summary.manualJournals' }, { label: 'Statut', path: 'status' }], controls: ['Hors horaires', 'Remises', 'Journaux', 'Paie'] },
  { key: 'customerProfitability', title: 'Profitabilité client', domain: 'Analytics', route: '/enterprise-operations/customer-profitability-report-page', description: 'Rapport profitabilité client par marge facture, support, livraison, remises et délai paiement.', metrics: [{ label: 'Clients', path: 'rows', format: 'count' }, { label: 'Profitabilité', path: 'rows.0.profitability', format: 'money' }, { label: 'Statut', path: 'status' }], controls: ['Marge', 'Support', 'Livraison', 'Délai paiement'] },
];

export const enterpriseOperationsFeatureByKey = Object.fromEntries(
  enterpriseOperationsFeatureDefinitions.map((definition) => [definition.key, definition]),
) as Record<EnterpriseOperationsFeatureKey, EnterpriseOperationsFeatureDefinition>;
